import { Theme, Icons } from "../../theme.slint";
import { Store, SettingDetailIndex } from "../../store.slint";
import { Logic } from "../../logic.slint";

import { Label, Head } from "../../base/widgets.slint";

component TopHead inherits Head {
    icon: Icons.home-fill;
    title: Logic.tr("Home");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits Rectangle {
    Label {
        text: "HOME";
    }
}

export component Home inherits Rectangle {
    VerticalLayout {
        TopHead { }

        Body { }
    }
}
