import { Theme, Store, TabIndex, SettingDetailIndex, Logic, Icons } from "../def.slint";
import { SettingDialog, AboutDialog, SettingIconsBar } from "../setting/desktop.slint";
import { Blanket, StatusBar, Divider, AboutSetting } from "../../base/widgets.slint";


export component DesktopPanel inherits Rectangle {
    private property <bool> is-show-setting-dialog: !(Store.current-setting-detail-index == SettingDetailIndex.None || Store.current-setting-detail-index == SettingDetailIndex.About);
    private property <bool> is-show-about-dialog: Store.current-setting-detail-index == SettingDetailIndex.About;

    VerticalLayout {
        if Store.setting-ui.no-frame: StatusBar {
            background: Theme.secondary-background;
            is-show-icon: true;
            icon: Icons.brand;
            title: AboutSetting.app-name;

            HorizontalLayout {
                padding-right: Theme.padding * 2;
                SettingIconsBar {
                    icon-size: Theme.default-font-size;
                    h-spacing: Theme.spacing * 3;
                    show-icon-hover-background: false;
                }

                VerticalLayout {
                    alignment: LayoutAlignment.center;
                    Divider {
                        height: Theme.default-font-size;
                        width: 2px;
                    }
                }
            }
        }

        VerticalLayout {
            padding: Theme.padding * 2;
            alignment: LayoutAlignment.end;
            HorizontalLayout {
                alignment: LayoutAlignment.center;

                SettingIconsBar {
                    background: Theme.secondary-background;
                    h-padding: Theme.spacing * 2;
                    h-spacing: Theme.padding * 5;
                }
            }
        }
    }

    if is-show-setting-dialog || is-show-about-dialog: Blanket {
        clicked => {
            Logic.switch-setting-detail(SettingDetailIndex.None);
        }
    }

    SettingDialog {
        visible: is-show-setting-dialog;
        width: Math.min(1300px, root.width * 0.8);
        height: Math.min(650px, root.height * 0.8);
    }

    if is-show-about-dialog: AboutDialog {
        width: Math.min(1300px, root.width * 0.8);
        height: Math.min(650px, root.height * 0.8);
    }
}
