import { Util, Theme, Icons, Logic } from "../../def.slint";
import { ExampleComponent, DatePicker, DatePickerPopup } from "../../../base/widgets.slint";

export component DatePickerExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;
    interactive: false; // disable dragging

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.min(1000px, root.width * 0.8);

                VerticalLayout {
                    spacing: Theme.spacing * 10;

                    HorizontalLayout {
                        alignment: center;

                        DatePicker {
                            canceled => {
                            }
                            confirmed(date) => {
                                debug(date);
                            }
                        }
                    }

                    HorizontalLayout {
                        alignment: center;
                        Rectangle {
                            background: gray;
                            width: txt.preferred-width + Theme.padding * 4;
                            height: txt.preferred-height + Theme.padding * 2;

                            txt := Text {
                                text: "Show DatePicker";
                            }

                            TouchArea {
                                clicked => {
                                    dp.show();
                                }
                            }
                        }
                    }
                }

                code: "DatePicker {\n    canceled => {\n    }\n    confirmed(date) => {\n        debug(date);\n    }\n}\n\n DatePickerPopup {\n    x: (root.width - self.width) / 2;\n    y: (root.height - self.height) / 2;\n}";
            }
        }
    }

    dp := DatePickerPopup {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
    }
}
