import { Util, Theme, Icons, Logic } from "../../def.slint";
import {
    NoMessageImg,
    NoDataImg,
    ExampleComponent,
    BlankWelcome,
} from "../../../base/widgets.slint";

export component EmptyExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;
    interactive: false; // disable dragging

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        VerticalLayout {
            spacing: Theme.spacing * 10;

            HorizontalLayout {
                width: root.width;
                alignment: LayoutAlignment.center;

                ExampleComponent {
                    width: Math.min(1000px, root.width * 0.8);

                    HorizontalLayout {
                        spacing: Theme.spacing * 10;

                        NoMessageImg {
                            width: 500px;
                            img-width: 300px;
                            text: Logic.tr("No Message");
                        }

                        NoDataImg {
                            width: 500px;
                            text: Logic.tr("No Data");
                        }
                    }

                    code: "HorizontalLayout {\n    spacing: Theme.spacing * 10;\n\n    NoMessageImg {\n        width: 500px;\n        img-width: 300px;\n        text: Logic.tr(\"No Message\");\n    }\n\n    NoDataImg {\n        width: 500px;\n        text: Logic.tr(\"No Data\");\n    }\n}";
                }
            }

            HorizontalLayout {
                width: root.width;
                alignment: LayoutAlignment.center;
                ExampleComponent {
                    width: Math.min(1000px, root.width * 0.8);

                    BlankWelcome {
                        height: root.height * Theme.golden-ratio;
                        width: parent.width;
                        title: "Welcome to use slint-template";
                        sub-title: "It's a template project for slint GUI framework";
                    }

                    code: "BlankWelcome {\n    title: \"Welcome to use slint-template\";\n    sub-title: \"It's a template project for slint GUI framework\";\n}";
                }
            }
        }
    }
}
