import { Util, Theme, Icons, Logic } from "../../def.slint";
import { ExampleComponent, FlickableWithScrollBar } from "../../../base/widgets.slint";

export component FlickableWithScrollBarExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;
    interactive: false; // disable dragging

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.min(1000px, root.width * 0.8);

                FlickableWithScrollBar {
                    height: 500px;
                    scrollbar-size: 20px;

                    VerticalLayout {
                        spacing: Theme.spacing * 2;
                        for index in 10: Rectangle {
                            background: red;
                            height: 100px;
                            width: root.width * 1.5;

                            Text {
                                text: index;
                                font-size: Theme.title1-font-size;
                            }
                        }
                    }
                }

                code: "FlickableWithScrollBar {\n    height: 500px;\n    scrollbar-width: 20px;\n\n    VerticalLayout {\n        spacing: Theme.spacing * 2;\n        for index in 10: Rectangle {\n            background: red;\n            height: 100px;\n            width: root.width * 1.5;\n\n           Text {\n                text: index;\n                font-size: Theme.title1-font-size;\n            }\n        }\n    }\n}";
            }
        }
    }
}
