import { Util, Store, Theme, Icons } from "../../def.slint";
import { Help, AboutSetting, ExampleComponent } from "../../../base/widgets.slint";

export component HelpExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.min(1000px, root.width * 0.8);

                Help {
                    width: 60%;
                    background: Theme.secondary-background;
                    border-radius: Theme.border-radius;

                    HorizontalLayout {
                        alignment: LayoutAlignment.center;
                        Rectangle {
                            width: 200px;
                            height: 200px;
                            background: red;
                        }
                    }
                }

                code: "Help {\n    width: 60%;\n    is-show-header: false;\n    background: Theme.secondary-background;\n    border-radius: Theme.border-radius;\n\n}";
            }
        }
    }
}
