import { Util, Theme, Icons, Logic } from "../../def.slint";
import {
    ExampleComponent,
} from "../../../base/widgets.slint";
import { SoundWaveForm } from "../../../base/sound-wave-form.slint";

export component SoundWaveFormExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;
    interactive: false; // disable dragging

    // Simple sample data
    private property <[float]> sine-wave-data: [
        0.1,
        0.1,
        0.2,
        0.3,
        0.4,
        0.5,
        0.6,
        0.7,
        0.8,
        0.9,
        1.0,
        0.9,
        0.8,
        0.7,
        0.6,
        0.5,
        0.4,
        0.3,
        0.2,
        0.1,
        0.1,
        -0.1,
        -0.2,
        -0.3,
        -0.4,
        -0.5,
        -0.6,
        -0.7,
        -0.8,
        -0.9,
        -1.0,
        -0.9,
        -0.8,
        -0.7,
        -0.6,
        -0.5,
        -0.4,
        -0.3,
        -0.2,
        -0.1,
        0.1,
    ];

    private property <[float]> noise-data: [
        0.1,
        -0.3,
        0.7,
        -0.2,
        0.5,
        -0.8,
        0.3,
        -0.1,
        0.6,
        -0.4,
        0.2,
        -0.7,
        0.8,
        -0.3,
        0.4,
        -0.6,
        0.7,
        -0.2,
        0.5,
        -0.9,
        0.3,
        -0.1,
        0.6,
        -0.4,
        0.2,
        -0.8,
        0.7,
        -0.3,
        0.5,
        -0.1,
        0.4,
        -0.6,
        0.8,
        -0.2,
        0.3,
        -0.7,
        0.6,
        -0.4,
        0.2,
        -0.5,
        0.7,
        -0.1,
        0.4,
        -0.8,
        0.5,
        -0.3,
        0.6,
        -0.2,
        0.3,
        -0.9
    ];

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        // Basic Wave Form Example
        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.min(1000px, root.width * 0.8);

                VerticalLayout {
                    spacing: Theme.spacing * 10;

                    Text {
                        text: "Interactive Wave";
                        font-size: Theme.title4-font-size;
                        color: Theme.primary-text-color;
                        horizontal-alignment: center;
                        wrap: word-wrap;
                    }

                    wave-display := SoundWaveForm {
                        width: Math.min(1000px, root.width * 0.8);
                        wave-data: sine-wave-data;
                        wave-color: Theme.brand-color;
                        is-mono: true;

                        moved(precent) => {
                            debug(precent);
                        }
                    }
                }

                code: "SoundWaveForm {\n    height: 200px;\n    wave-data: sineWaveData; // Float array\n}";
            }
        }

        // Noise Example
        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.min(1000px, root.width * 0.8);

                VerticalLayout {
                    spacing: Theme.spacing * 10;

                    Text {
                        text: "Random Noise";
                        font-size: Theme.title4-font-size;
                        color: Theme.primary-text-color;
                        horizontal-alignment: center;
                    }

                    SoundWaveForm {
                        init => {
                            let random_data = Logic.generate-sound-data(1000);
                            if (random-data.length > 0) {
                                self.wave-data = random-data;
                            }
                        }

                        width: Math.min(1000px, root.width * 0.8);
                        wave-data: noise-data;
                        wave-color: Theme.warning-color;
                        show-timestamp: true;
                        start-timestamp: "01:00";
                        end-timestamp: "05:00";
                    }
                }

                code: "SoundWaveForm {\n    height: 150px;\n    wave-data: noiseData;\n}";
            }
        }
    }
}
