import { Util, Theme } from "../../def.slint";
import { Stretch, Label, ExampleComponent } from "../../../base/widgets.slint";

export component StretchExample inherits Rectangle {
    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.min(1000px, root.width * 0.8);

                Stretch {
                    title: "A Stretch example(double click to expand)";
                    is-show-indicator: true;

                    title-clicked => {
                        self.is-checked = !self.is-checked;
                    }

                    title-double-clicked => {
                        self.is-show-children = !self.is-show-children;
                    }

                    body-clicked => {
                        self.is-checked = !self.is-checked;
                    }

                    Label {
                        text: "查看启动信息：系统启动时，内核会记录硬件检测、驱动加载等信息 调试硬件问题：通过dmesg可以查看硬件设备是否被正确识别和初始化。 监控内核事件：实时查看内核产生的日志，帮助诊断系统问题。";
                        font-size: Theme.default-font-size;
                        color: Theme.regular-text-color;
                        wrap: word-wrap;
                    }
                }

                code: "Stretch {\n                    width: root.width * 0.5;\n                    title: \"A Stretch example(doubleclick to expand)\";\n                    is-show-indicator: true;\n\n                    title-clicked => {\n                        self.is-checked = !self.is-checked;\n                    }\n\n                    title-double-clicked => {\n                        self.is-show-children = !self.is-show-children;\n                    }\n\n                    body-clicked => {\n                        self.is-checked = !self.is-checked;\n                    }\n\n                    Label {\n                        text: \"查看启动信息：系统启动时，内核会记录硬件检测、驱动加载等信息 调试硬件问题：通过dmesg可以查看硬件设备是否被正确识别和初始化。 监控内核事件：实时查看内核产生的日志，帮助诊断系统问题。\";\n                        font-size: Theme.default-font-size;\n                        color: Theme.regular-text-color;\n                        wrap: word-wrap;\n                    }\n}\n";
            }
        }
    }
}
