import { Util, Theme } from "../../def.slint";
import { TodoList, TodoEntry, ExampleComponent } from "../../../base/widgets.slint";

export component TodoListExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;
    interactive: false; // disable dragging

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.min(1000px, root.width * 0.8);

                HorizontalLayout {
                    alignment: LayoutAlignment.center;

                    TodoList {
                        width: parent.width * 80%;
                        height: 300px;
                        entries: [
                            {
                                uuid: "uuid-1",
                                title: "text-1",
                                detail: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
                                is-open: true,
                            },
                            {
                                uuid: "uuid-2",
                                title: "text-2",
                                detail: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
                                is-open: false,
                            },
                        ];
                    }
                }

                detail: "callback clicked()\ncallback double-clicked()";

                code: "TodoList {\n    width: root.width * 40%;\n    height: 500px;\n    entries: [\n         {\n            uuid: \"uuid-1\",\n            title: \"text-1\",\n            detail: \"In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods\",\n            is-open: true,\n         },\n         {\n            uuid: \"uuid-2\",\n            title: \"text-2\",\n            detail: \"In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods\",\n            is-open: false,\n         },\n    ];\n}";
            }
        }
    }
}
