import { Theme } from "../../theme.slint";
import { Store, MobileTabIndex, MobileSettingDetailIndex } from "../../store.slint";
import { Home } from "./home.slint";
import { Setting } from "../setting/mobile.slint";
import { Footer } from "footer.slint";

export component Bodyer inherits Rectangle {
    if MobileTabIndex.Home == Store.current-mobile-tab-index: Home { }
    if MobileTabIndex.Setting == Store.current-mobile-tab-index: Setting { }
}

export component MobilePanel inherits Rectangle {
    background: Theme.base-background;

    VerticalLayout {
        padding-left: Theme.padding;
        padding-right: Theme.padding;

        property <bool> isShowFooter: Store.current-mobile-tab-index == MobileTabIndex.Home || (Store.current-mobile-tab-index == MobileTabIndex.Setting && Store.current-mobile-setting-detail-index == MobileSettingDetailIndex.Home);

        Bodyer {
            height: parent.height - (isShowFooter ? (Theme.footer-height + Theme.padding) : 0);
        }

        if isShowFooter:  Footer { }
    }
}
