import { Blanket, ToolTip, ToolTipSetting, PopupAction, PopupActionSetting } from "../../base/widgets.slint";

import { Home } from "./home.slint";

export component WebPanel inherits Rectangle {
    Home { }

    if false: Blanket {
        clicked => {
        }
    }

    if PopupActionSetting.is-show: PopupAction {
        window-width: root.width;
        window-height: root.height;
    }

    if ToolTipSetting.is-show: ToolTip {
        window-width: root.width;
        window-height: root.height;
    }
}
