import { Util, Theme, Icons } from "../../def.slint";
import { AccountBalance, ExampleComponent } from "../../../base/widgets.slint";

export component AccountBalanceExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                AccountBalance {
                    account-name: "Account 1";
                    balance: "$100";
                    background: Theme.secondary-background;
                    border-radius: Theme.border-radius;

                    name-clicked => {
                    }
                    copy => {
                    }
                }

                code: "AccountBalance {\n    account-name: \"Account 1\";\n    balance: \"$100\";\n    background: Theme.secondary-background;\n    border-radius: Theme.border-radius;\n\n    name-clicked => {\n    }\n    copy => {\n    }\n}";
            }
        }
    }
}
