import { Util, Theme, Icons } from "../../def.slint";
import { Brand, ExampleComponent } from "../../../base/widgets.slint";

export component BrandExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                Brand {
                    width: 500px;
                    source: Icons.brand;
                }

                code: "Brand {\n    width: 500px;\n}";
            }
        }
    }
}
