import { Util, Theme } from "../../def.slint";
import { Label, ExampleComponent } from "../../../base/widgets.slint";

export component LabelExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                Rectangle {
                    width: lb.preferred-width + Theme.padding * 4;
                    height: lb.preferred-height + Theme.padding * 2;
                    background: Theme.secondary-background;
                    border-radius: Theme.border-radius;

                    lb := Label {
                        text: "This is a label";
                        color: Colors.red;
                    }
                }

                code: "Rectangle {\n    width: lb.preferred-width + Theme.padding * 4;\n    height: lb.preferred-height + Theme.padding * 2;\n    background: Theme.secondary-background;\n    border-radius: Theme.border-radius;\n\n    lb := Label {\n        text: \"This is a label\";\n        color: Colors.red;\n    }\n}";
            }
        }
    }
}
