import { Util, Theme } from "../../def.slint";
import { Link, ExampleComponent } from "../../../base/widgets.slint";

export component LinkExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                Link {
                    text: "Your blog's page";
                    clicked => {
                        debug("clicked");
                    }
                }

                code: "Link {\n    text: \"Your blog's page\";\n    clicked => {\n        debug(\"clicked\");\n    }\n}";
            }
        }
    }
}
