import { Util, Theme, Icons } from "../../def.slint";
import { Password, ExampleComponent } from "../../../base/widgets.slint";

export component PasswordExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                Password {
                    back => {
                    }

                    canceled() => {
                    }

                    confirmed(handle-type, password, user-data) => {
                        return "Error Message";
                    }
                }

                code: "Password {\n    back => {\n    }\n\n    canceled() => {\n    }\n\n    confirmed(handle-type, password, user-data) => {\n        return \"Error Message\";\n    }\n}";
            }
        }
    }
}
