import { Util, Theme, Store } from "../../def.slint";
import { PinCodes,PinCodesCount, ExampleComponent } from "../../../base/widgets.slint";

export component PinCodesExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                VerticalLayout {
                    spacing: Theme.spacing * 10;

                    for item in [PinCodesCount.Four, PinCodesCount.Six, PinCodesCount.Eight]: PinCodes {
                        count: item;

                        finished(codes) => {
                            if (item == PinCodesCount.Four) {
                                debug(codes[0],codes[1], codes[2], codes[3]);
                            } else if (item == PinCodesCount.Six) {
                                debug(codes[0],codes[1], codes[2], codes[3], codes[4], codes[5]);
                            } else {
                                debug(codes[0],codes[1], codes[2], codes[3], codes[4], codes[5],codes[6], codes[7], codes[8]);
                            }
                        }
                    }
                }

                detail: Store.is-cn ? "按回车键完成输入" : "Press 'Enter' key to finish inputting";
                code: "for item in [PinCodesCount.Four, PinCodesCount.Six, PinCodesCount.Eight]: PinCodes {\n    count: item;\n\n    finished(codes) => {\n        if (item == PinCodesCount.Four) {\n            debug(codes[0],codes[1], codes[2], codes[3]);\n        } else if (item == PinCodesCount.Six) {\n            debug(codes[0],codes[1], codes[2], codes[3], codes[4], codes[5]);\n        } else {\n            debug(codes[0],codes[1], codes[2], codes[3], codes[4], codes[5],codes[6], codes[7], codes[8]);\n        }\n    }\n}";
            }
        }
    }
}
