import { Util, Theme } from "../../def.slint";
import { Rate, ExampleComponent } from "../../../base/widgets.slint";

export component RateExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                Rate {
                    count: 5;
                    rate: 2;
                    icon-size: Theme.icon-size * 2;
                }

                code: "Rate {\n    count: 5;\n    rate: 2;\n    icon-size: Theme.icon-size * 2;\n}";
            }
        }
    }
}
