import { Util, Theme, Icons } from "../../def.slint";
import { Label, ResetPassword, ExampleComponent } from "../../../base/widgets.slint";

export component ResetPasswordExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                ResetPassword {
                    back => {
                    }
                    canceled => {
                    }

                    confirmed(old-password, new-password-first, new-password-second) => {
                        return "Error Message";
                    }
                }

                code: "ResetPassword {\n    back => {\n    }\n    canceled => {\n    }\n\n    confirmed(old-password, new-password-first, new-password-second) => {\n        return \"Error Message\";\n    }\n}";
            }
        }
    }
}
