import { Util, Theme, Icons } from "../../def.slint";
import { SignIn, ExampleComponent } from "../../../base/widgets.slint";

export component SignInExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                SignIn {
                    back => {
                    }

                    confirmed(username, first-password, second-password) => {
                        return "Error Message";
                    }
                }

                code: "SignIn {\n    back => {\n    }\n\n    confirmed(username, first-password, second-password) => {\n        return \"Error Message\";\n    }\n}";
            }
        }
    }
}
