import { Util, Theme } from "../../def.slint";
import { Tag, ExampleComponent } from "../../../base/widgets.slint";

export component TagExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.max(1000px, root.width * 0.8);

                HorizontalLayout {
                    spacing: Theme.spacing * 2;
                    for color[index] in Theme.tag-colors: Tag {
                        background: color;
                        text-color: self.background.darker(100%);
                        text: "Tag";
                        is-show-close-btn: Math.mod(index, 2) == 1;

                        close => {}
                    }
                }

                code: "HorizontalLayout {\n    spacing: Theme.spacing * 2;\n    for color[index] in Theme.tag-colors: Tag {\n        background: color;\n        text-color: self.background.darker(100%);\n        text: \"Tag\";\n        is-show-close-btn: Math.mod(index, 2) == 1;\n        close => {}\n    }\n}";
            }
        }
    }
}
