import { Tree } from "../../../base/widgets.slint";

export component TreeExample inherits Rectangle {
    Tree {
        level-one-entries: [{
            is-open: true,
            current-node: "亚洲",
        }, {
            current-node: "北美洲",
        }];

        level-two-entries: [
            {
                is-open: true,
                parent-node: "亚洲",
                current-node: "中国",
            },
            {
                parent-node: "北美洲",
                current-node: "美国",
            }
        ];

        level-three-entries: [
            {
                parent-node: "中国",
                current-node: "珠海",
                key: "zhuhai",
            },
            {
                parent-node: "中国",
                current-node: "广州",
                key: "guangzhou",
            },
            {
                parent-node: "美国",
                current-node: "纽约",
            },
            {
                parent-node: "美国",
                current-node: "加州",
            }
        ];

        clicked(entries, path, key) => {
            debug(entries[0], entries[1], entries[3]);
            debug(path);
            debug(key);
        }
    }
}
