import { Util, Theme, Icons } from "../../def.slint";
import { VideoControl, ExampleComponent } from "../../../base/widgets.slint";

export component VideoControlExample inherits Flickable {
    viewport-height: vbox.preferred-height;
    viewport-width: vbox.preferred-width;

    vbox := VerticalLayout {
        spacing: Theme.spacing * 20;
        padding-top: Theme.padding * 5;
        padding-bottom: Theme.padding * 5;
        alignment: LayoutAlignment.center;

        HorizontalLayout {
            width: root.width;
            alignment: LayoutAlignment.center;

            ExampleComponent {
                width: Math.min(1000px, root.width * 0.8);

                VideoControl { }

                code: "";
            }
        }
    }
}
