#[cfg(any(
    target_os = "windows",
    target_os = "linux",
    target_os = "macos",
    target_os = "android"
))]
use crate::config;

use std::collections::HashMap;

pub fn tr(text: &str) -> String {
    #[cfg(any(
        target_os = "windows",
        target_os = "linux",
        target_os = "macos",
        target_os = "android"
    ))]
    {
        if config::preference().language == "en" {
            return text.to_string();
        }
    }

    let items: HashMap<&str, &str> = HashMap::from([
        ("about", "关于"),
        ("About", "关于"),
        ("Account address", "账户地址"),
        ("Address", "地址"),
        ("Address book", "地址簿"),
        ("Address name", "地址名称"),
        ("Advance setting", "高级设置"),
        ("Apply", "应用"),
        ("At least 8 chars", "至少8个字符"),
        ("Back", "返回"),
        ("Base fee", "基础费用"),
        ("Blockchain network", "区块链网络"),
        ("Cancel", "取消"),
        ("Checked", "已选中"),
        ("Choose language", "选择语言"),
        ("Choose Theme", "选择主题"),
        ("close", "关闭"),
        ("Close", "关闭"),
        ("Confirm", "确认"),
        ("Copy failed", "复制失败"),
        ("Copy success", "复制成功"),
        ("Create token account fee", "创建代币账户费用"),
        ("Danger", "危险"),
        ("Dark", "暗色"),
        ("Delete", "删除"),
        ("Delete address", "删除地址"),
        ("Delete address or not?", "是否删除地址？"),
        ("Delete or not?", "是否删除？"),
        ("Disable", "禁用"),
        ("Donate", "捐赠"),
        ("Evaluating gas fee...", "估算燃气费中..."),
        ("Evaluating transaction fee failed", "估算交易费失败"),
        ("Fast", "快速"),
        ("Finished", "已完成"),
        ("Font family", "字体"),
        ("Font size", "字体大小"),
        ("Frameless window", "无边框窗口"),
        ("github", "github"),
        ("Github", "Github"),
        ("height", "高度"),
        ("Help", "帮助"),
        ("Home", "首页"),
        ("Icons", "图标"),
        ("Info", "信息"),
        ("Input can not be empty", "输入不能为空"),
        ("Jump to", "跳转到"),
        ("keyword", "关键词"),
        ("Light", "亮色"),
        ("Log in", "登录"),
        ("maximal", "最大"),
        ("Memo", "备注"),
        ("MetaMask crypto pay", "MetaMask加密支付"),
        ("minimal", "最小"),
        ("mnemonics", "助记词"),
        ("No Data", "无数据"),
        ("No Message", "无消息"),
        ("normal", "普通"),
        ("Normal", "普通"),
        ("Open link failed", "打开链接失败"),
        ("Password", "密码"),
        ("Paste failed", "粘贴失败"),
        ("Please enter new password", "请输入新密码"),
        ("Please enter old password", "请输入旧密码"),
        ("Please enter password", "请输入密码"),
        ("Please enter password again", "请再次输入密码"),
        ("Please enter username", "请输入用户名"),
        ("Please select language", "请选择语言"),
        ("Preference", "偏好设置"),
        ("Prev", "上一步"),
        ("Prioritization fee", "优先费用"),
        ("Proxy", "代理"),
        ("Proxy address", "代理地址"),
        ("Proxy port", "代理端口"),
        ("Quit application or not?", "是否退出应用？"),
        ("Reason", "原因"),
        ("Reboot to take setting effect", "重启以应用设置"),
        ("Recipient address", "收款地址"),
        ("Refreshing...", "刷新中..."),
        ("Reset password", "重置密码"),
        ("Search", "搜索"),
        ("Send address", "发送地址"),
        ("Send amount", "发送金额"),
        ("Send token", "发送代币"),
        ("setting", "设置"),
        ("Setting", "设置"),
        ("Sign in", "登录"),
        ("Skip", "跳过"),
        ("Slow", "慢速"),
        ("Success", "成功"),
        ("TokenListWithSwitch", "代币列表（带切换）"),
        ("Transaction detail", "交易详情"),
        ("Transaction failed", "交易失败"),
        ("Transaction history", "交易历史"),
        ("Transaction signature", "交易签名"),
        ("Transaction success", "交易成功"),
        ("Unchecked", "未选中"),
        ("Username", "用户名"),
        ("Waiting transaction confirmed...", "等待交易确认中..."),
        ("Warning", "警告"),
        ("Wechat pay", "微信支付"),
        ("width", "宽度"),
        ("Window always on top", "窗口置顶"),
        ("Window height", "窗口高度"),
        ("Window size", "窗口大小"),
        ("Window width", "窗口宽度"),
    ]);

    if let Some(txt) = items.get(text) {
        return txt.to_string();
    }

    text.to_string()
}
