import { LineEdit, ComboBox } from "std-widgets.slint";
import { Theme, Logic, Store, Icons, SettingUI, DeviceType } from "../../def.slint";
import { SettingDetailInner, SettingDetail, SettingDetailInnerVbox, SettingDetailLabel, RadioBtn, SettingDetailSwitch } from "../../../base/widgets.slint";

export component Preference inherits SettingDetail {
    title: Logic.tr("Preference");

    public function get() -> SettingUI {
        return {
            font-size: font-size-lineedit.text,
            font-family: fonts-combox.current-value,
            is-use-system-bar: Store.setting-ui.is-use-system-bar,
            language: Store.setting-ui.language,
            is-dark: Store.setting-ui.is-dark,
        };
    }

    init => {
        font-size-lineedit.text = Store.setting-ui.font-size;
        fonts-combox.current-value = Store.setting-ui.font-family;
    }

    SettingDetailInner {
        SettingDetailInnerVbox {
            font-size-txt := SettingDetailLabel {
                text: Logic.tr("Font size");
            }

            font-size-lineedit := LineEdit {
                input-type: number;
                height: font-size-txt.preferred-height * 1.6;
                placeholder-text: Logic.tr("10 ~ 50");
                text: Store.setting-ui.font-size;
            }
        }

        SettingDetailInnerVbox {
            fonts-label := SettingDetailLabel {
                text: Logic.tr("Font family");
            }

            fonts-combox := ComboBox {
                height: fonts-label.preferred-height * 1.6;
                model: ["Default", "Source Han Serif CN", "Source Han Sans CN"];
                current-value: Store.setting-ui.font-family;
            }
        }

        if Store.device-type == DeviceType.Desktop: SettingDetailInnerVbox {
            system-bar-switch := SettingDetailSwitch {
                icon: Icons.status;
                text: Logic.tr("Enable system status bar");
                checked: Store.setting-ui.is-use-system-bar;
                toggle => {
                    Store.setting-ui.is-use-system-bar = self.checked;
                    Logic.set-setting-ui(root.get());
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Choose language");
            }

            HorizontalLayout {
                HorizontalLayout {
                    width: 50%;
                    cn-radio := RadioBtn {
                        text: "中文";
                        checked: Store.setting-ui.language == "cn";
                        check => {
                            Store.setting-ui.language = "cn";
                            Logic.set-setting-ui(root.get());
                        }
                    }
                }

                en-radio := RadioBtn {
                    text: "English";
                    checked: Store.setting-ui.language == "en";
                    check => {
                        Store.setting-ui.language = "en";
                        Logic.set-setting-ui(root.get());
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Choose Theme");
            }

            HorizontalLayout {
                HorizontalLayout {
                    width: 50%;
                    RadioBtn {
                        text: Logic.tr("Light");
                        checked: !Theme.is-dark;
                        check => {
                            Theme.toggle();
                        }
                    }
                }

                RadioBtn {
                    text: Logic.tr("Dark");
                    checked: Theme.is-dark;
                    check => {
                        Theme.toggle();
                    }
                }
            }
        }
    }
}
