use regex::Regex;

const TR_FILE_CONTENT: &str = include_str!("../slint-template/src/logic/tr.rs");

fn main() {
    let clean_contents = remove_cfg_blocks(TR_FILE_CONTENT);
    let clean_contents = format!("// Auto-generated by build.rs.\n{}", clean_contents);
    std::fs::write("src/tr.rs", clean_contents).unwrap();
}

fn remove_cfg_blocks(input: &str) -> String {
    let cfg_block_re = Regex::new(r"(?s)#\[cfg\(any\(.*?\)\)]\s*\{\s*lang = .*?\}").unwrap();

    let result = cfg_block_re.replace_all(input, "").to_string();
    result
        .replace("#[allow(unused_assignments)]", "")
        .replace(r#"let mut lang = "en".to_string();"#, "")
        .replace("tr(text: &str)", "tr(text: &str, lang: String)")
        .to_string()
}
