use regex::Regex;

const TR_FILE_CONTENT: &str = include_str!("../slint-template/src/logic/tr.rs");

fn main() {
    let clean_contents = remove_cfg_blocks(TR_FILE_CONTENT);
    let clean_contents = format!("// Auto-generated by build.rs.\n{}", clean_contents);

    std::fs::write("src/tr.rs", clean_contents).unwrap();
}

fn remove_cfg_blocks(input: &str) -> String {
    // 匹配 `#[cfg(any(...))] use crate::config;` 部分
    let cfg_use_re = Regex::new(r"(?s)#\[cfg\(any\(.*?\)\)]\s*use crate::config;").unwrap();

    // 匹配 `#[cfg(any(...))] { if config::preference()... }` 部分
    let cfg_block_re = Regex::new(r"(?s)#\[cfg\(any\(.*?\)\)]\s*\{\s*lang = .*?\}").unwrap();

    // 分步替换
    let result = cfg_use_re.replace_all(input, "").to_string();
    let result = cfg_block_re.replace_all(&result, "").to_string();
    result
        .replace("#[allow(unused_assignments)]", "")
        .replace(r#"let mut lang = "en".to_string();"#, "")
        .replace("tr(text: &str)", "tr(text: &str, lang: String)")
        .to_string()
}
