import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Head, Label } from "../../base/widgets.slint";

component TopHead inherits Head {
    icon: Icons.home-fill;
    title: Logic.tr("Home");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits Rectangle {
    Label {
        text: "HOME";
        font-size: Theme.title1-font-size;
    }
}

export component Home inherits Rectangle {
    VerticalLayout {
        TopHead { }

        Body { }
    }
}
