import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Head, Label, TabBtns, ConfirmBtn } from "../../base/widgets.slint";

component TopHead inherits Head {
    icon: Icons.home-fill;
    title: Logic.tr("Home");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits Rectangle {
    VerticalLayout {
        alignment: center;
        spacing: Theme.spacing * 2;

        HorizontalLayout {
            alignment: center;
            TabBtns {
                items: [
                    { icon: Icons.cancel-fill, text: "Cancel" },
                    { icon: Icons.address, text: "Address" },
                    { icon: Icons.airdrop, text: "Airdrop" }
                ];
            }
        }

        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                alignment: center;
                ConfirmBtn { }
            }
        }
    }
}

export component Home inherits Rectangle {
    VerticalLayout {
        TopHead { }

        Body { }
    }
}
