import { Logic, Theme, Store, Util, Icons, SettingPreference, SettingProxy, SettingDetailIndex, DeviceType, TabIndex } from "../def.slint";
import { IconBtn, SettingEntryV2, Head, SettingDetail, ToastStatus, About, Help, Dialog, ComponentPosition } from "../../base/widgets.slint";
import { Preference } from "components/preference.slint";
import { Donate } from "components/donate.slint";
import { Proxy } from "components/proxy.slint";

component LeftPanel inherits Rectangle {
    background: Theme.secondary-background;

    Flickable {
        width: root.width;
        viewport-height: vbox.preferred-height;

        vbox := VerticalLayout {
            alignment: LayoutAlignment.start;

            SettingEntryV2 {
                text: Logic.tr("Preference");
                icon: Icons.ui;
                background: Store.current-setting-detail-index == SettingDetailIndex.Preference ? Theme.checked-background : self.has-hover ? Theme.hover-background : root.background;

                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.Preference);
                }
            }

            SettingEntryV2 {
                text: Logic.tr("Proxy");
                icon: Icons.proxy-light;
                background: Store.current-setting-detail-index == SettingDetailIndex.Proxy ? Theme.checked-background : self.has-hover ? Theme.hover-background : root.background;

                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.Proxy);
                }
            }

            SettingEntryV2 {
                text: Logic.tr("Help");
                icon: Icons.help-light;
                background: Store.current-setting-detail-index == SettingDetailIndex.Help ? Theme.checked-background : self.has-hover ? Theme.hover-background : root.background;

                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.Help);
                }
            }

            SettingEntryV2 {
                text: Logic.tr("Donate");
                icon: Icons.donate-light;
                background: Store.current-setting-detail-index == SettingDetailIndex.Donate ? Theme.checked-background : self.has-hover ? Theme.hover-background : root.background;

                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.Donate);
                }
            }
        }
    }
}

component RightPanel inherits Rectangle {
    background: Theme.base-background;

    public function apply() {
        if (Store.current-setting-detail-index == SettingDetailIndex.Preference) {
            preference.apply();
        } else if (Store.current-setting-detail-index == SettingDetailIndex.Proxy) {
            proxy.apply();
        }
    }

    init => {
        Logic.switch-setting-detail(SettingDetailIndex.Preference);
    }

    preference := Preference {
        visible: Store.current-setting-detail-index == SettingDetailIndex.Preference;
        is-show-header: false;

        public function apply() {
            if (self.get().font-size == "" || self.get().win-width == "" || self.get().win-height == "") {
                Util.show-toast(Logic.tr("Input can not be empty"), ToastStatus.Warning);
                return;
            }
            Store.setting-preference.win-width = self.get().win-width;
            Store.setting-preference.win-height = self.get().win-height;
            Store.setting-preference.font-size = self.get().font-size;
            Store.setting-preference.font-family = self.get().font-family;

            Logic.set-setting-preference(self.get());
        }
    }

    proxy := Proxy {
        visible: Store.current-setting-detail-index == SettingDetailIndex.Proxy;
        is-show-header: false;

        public function apply() {
            Logic.set-setting-proxy(self.get());
        }
    }

    if Store.current-setting-detail-index == SettingDetailIndex.Help: Help {
        is-show-header: false;
    }

    if Store.current-setting-detail-index == SettingDetailIndex.Donate: Donate {
        is-show-header: false;
    }
}

component Setting inherits Rectangle {
    public function apply() {
        rp.apply();
    }

    lp := LeftPanel {
        x: 0;
        width: Math.max(root.width * 0.3, Theme.title3-font-size * 10);
    }

    mp := Rectangle {
        x: lp.width;
        width: Theme.padding;

        TouchArea {
            mouse-cursor: MouseCursor.col-resize;
            moved => {
                lp.width = Math.min(Math.max(0px, lp.width - (self.pressed-x - self.mouse-x)), root.width - self.width)
            }
        }
    }

    rp := RightPanel {
        x: mp.x + mp.width;
        width: root.width - self.x;
    }
}

export component SettingDialog inherits Dialog {
    title: Logic.tr("Setting");
    is-hide-cancel-btn: true;
    is-prevent-event-forward: true;
    confirm-text: Logic.tr("Apply");

    in-out property <length> inner-height: 650px;

    setting := Setting {
        height: root.inner-height;
    }

    cancel-clicked => {
        Logic.switch-tab(TabIndex.Back);
    }

    ok-clicked => {
        setting.apply();
    }
}

export component AboutDialog inherits Dialog {
    title: Logic.tr("About");
    is-hide-bottom-btns: true;
    is-prevent-event-forward: true;

    in-out property <length> inner-height: 650px;

    About {
        height: root.inner-height;
        is-show-header: false;
    }

    cancel-clicked => {
        Logic.switch-tab(TabIndex.Back);
    }
}

export component HorizontalSettingIconsBar inherits Rectangle {
    width: hbox.preferred-width;
    height: hbox.preferred-height;
    border-radius: Theme.border-radius;

    in-out property <bool> show-icon-hover-background: false;
    in-out property <length> icon-size: Theme.icon-size;
    in-out property <bool> is-show-tip: false;
    in-out property <ComponentPosition> tip-position;
    in-out property h-padding <=> hbox.padding;
    in-out property h-spacing <=> hbox.spacing;

    hbox := HorizontalLayout {
        padding: Theme.padding * 2;
        spacing: Theme.spacing * 4;

        IconBtn {
            icon: Icons.setting-fill;
            icon-size: root.icon-size;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
            tip: Logic.tr("setting");

            clicked => {
                Logic.switch-tab(TabIndex.Setting);
            }
        }

        IconBtn {
            icon: Icons.about-fill;
            icon-size: root.icon-size;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
            tip: Logic.tr("about");

            clicked => {
                Logic.switch-tab(TabIndex.About);
            }
        }

        IconBtn {
            icon: Icons.github;
            icon-size: root.icon-size;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
            tip: Logic.tr("github");

            clicked => {
                Util.open-url("Default","https://github.com/Heng30/slint-template");
            }
        }
    }
}

export component VerticalSettingIconsBar inherits Rectangle {
    width: vbox.preferred-width;
    height: vbox.preferred-height;
    border-radius: Theme.border-radius;

    in-out property <bool> show-icon-hover-background: false;
    in-out property <length> icon-size: Theme.icon-size;
    in-out property <bool> is-show-tip: false;
    in-out property <ComponentPosition> tip-position;
    in-out property <length> v-padding-bottom;
    in-out property v-padding <=> vbox.padding;
    in-out property v-spacing <=> vbox.spacing;

    vbox := VerticalLayout {
        padding: Theme.padding * 2;
        padding-bottom: root.v-padding-bottom;
        spacing: Theme.spacing * 4;

        IconBtn {
            icon: Icons.setting-fill;
            icon-size: root.icon-size;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
            tip: Logic.tr("setting");

            clicked => {
                Logic.switch-tab(TabIndex.Setting);
            }
        }

        IconBtn {
            icon: Icons.about-fill;
            icon-size: root.icon-size;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
            tip: Logic.tr("about");

            clicked => {
                Logic.switch-tab(TabIndex.About);
            }
        }

        IconBtn {
            icon: Icons.github;
            icon-size: root.icon-size;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
            tip: Logic.tr("github");

            clicked => {
                Util.open-url("Default","https://github.com/Heng30/slint-template");
            }
        }
    }
}
