export enum DeviceType {
    Desktop,
    Mobile,
    Web,
}

export enum TabIndex {
    Home,
    Setting,
    About,
    Back,
}

export enum SettingDetailIndex {
    Preference,
    Proxy,
    Help,
    Donate,

    // Mobile
    Home,
    About,
}

export struct SettingPreference {
    win-width: string,
    win-height: string,
    font-size: string,
    font-family: string,
    language: string,
    always-on-top: bool,
    no-frame: bool,
    is-dark: bool,
}

export struct SettingProxy {
    proxy-type: string,
    http-url: string,
    http-port: string,
    socks5-url: string,
    socks5-port: string,
}

//////////////////////////////// Logic Struct Start ////////////////////////////////
import { SideBarEntry } from "./base/def.slint";

//////////////////////////////// Logic Struct End  ////////////////////////////////

export global Store {
    in-out property <DeviceType> device-type: DeviceType.Desktop;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page: false;

    in-out property <TabIndex> previous-tab-index: TabIndex.Home;
    in-out property <TabIndex> current-tab-index: TabIndex.Home;
    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Preference;

    in-out property <bool> is-cn: setting-preference.language == "cn";
    in-out property <SettingPreference> setting-preference: {
        win-width: 1000,
        win-height: 800,
        font-size: "16",
        font-family: "Source Han Sans CN",
        language: "en",
        always-on-top: false,
        no-frame: true,
        is-dark: false,
    };

    //////////////////////////////// Logic Start ////////////////////////////////
    in-out property <string> current-sidebar-key: "Introduction";
    in-out property <[SideBarEntry]> sidebar-entries: [
        {
            category: is-cn ? "介绍" : "Introduction",
            key: "Introduction",
        },
        // Base
        {
            category: is-cn ? "基础类" : "Base",
            is-open: true,
            children: [
                {
                    title: is-cn ? "按钮" : "Button",
                    key: "Button",
                },
                {
                    title: is-cn ? "文本" : "Label",
                    key: "Label",
                },
                {
                    title: is-cn ? "分割线" : "Divider",
                    key: "Divider",
                },
                {
                    title: is-cn ? "遮罩" : "Blanket",
                    key: "Blanket",
                },
                {
                    title: is-cn ? "中间布局" : "CenterLayout",
                    key: "CenterLayout",
                },
                {
                    title: is-cn ? "滑动卡片" : "SlideCard",
                    key: "SlideCard",
                },
                {
                    title: is-cn ? "抽屉" : "Drawer",
                    key: "Drawer",
                },
                {
                    title: is-cn ? "滚动区域" : "FlickableWithScrollBar",
                    key: "FlickableWithScrollBar",
                },
            ]
        },
        // Input
        {
            category: is-cn ? "输入类" : "Input",
            children: [
                {
                    title: is-cn ? "滑动条" : "Slider",
                    key: "Slider",
                },
                {
                    title: is-cn ? "打分" : "Rate",
                    key: "Rate",
                },
                {
                    title: is-cn ? "验证码" : "PinCodes",
                    key: "PinCodes",
                },
                {
                    title: is-cn ? "选择下拉栏" : "Select",
                    key: "Select",
                },
                {
                    title: is-cn ? "输入" : "Input",
                    key: "Input",
                },
                {
                    title: is-cn ? "注册" : "SignIn",
                    key: "SignIn",
                },
                {
                    title: is-cn ? "登陆" : "LogIn",
                    key: "LogIn",
                },
                {
                    title: is-cn ? "密码" : "Password",
                    key: "Password",
                },
                {
                    title: is-cn ? "重置密码" : "ResetPassword",
                    key: "ResetPassword",
                },
                {
                    title: is-cn ? "日期选择" : "DatePicker",
                    key: "DatePicker",
                },
            ]
        },
        // Navigation
        {
            category: is-cn ? "导航类" : "Navigation",
            children: [
                {
                    title: is-cn ? "侧边栏" : "SideBar",
                    key: "SideBar",
                },
                {
                    title: is-cn ? "树" : "Tree",
                    key: "Tree",
                },
                {
                    title: is-cn ? "分页" : "Pagination",
                    key: "Pagination",
                },
                {
                    title: is-cn ? "标签页" : "TabBtn",
                    key: "TabBtn",
                },
                {
                    title: is-cn ? "顶部状态栏" : "StatusBar",
                    key: "StatusBar",
                },
                {
                    title: is-cn ? "头部" : "Head",
                    key: "Head",
                },
            ]
        },
        // Display
        {
            category: is-cn ? "展示类" : "Display",
            children: [
                {
                    title: is-cn ? "徽章" : "Badge",
                    key: "Badge",
                },
                {
                    title: is-cn ? "步骤" : "Step",
                    key: "Step",
                },
                {
                    title: is-cn ? "进度条" : "Progress",
                    key: "Progress",
                },
                {
                    title: is-cn ? "弹出信息" : "Toast",
                    key: "Toast",
                },
                {
                    title: is-cn ? "录制指示器" : "RecordIndicator",
                    key: "RecordIndicator",
                },
                {
                    title: is-cn ? "工具提示" : "ToolTip",
                    key: "ToolTip",
                },
                {
                    title: is-cn ? "面包屑" : "BreadCrumb",
                    key: "BreadCrumb",
                },
                {
                    title: is-cn ? "骨架" : "Skeleton",
                    key: "Skeleton",
                },
                {
                    title: is-cn ? "折叠" : "Collapse",
                    key: "Collapse",
                },
                {
                    title: is-cn ? "伸展" : "Stretch",
                    key: "Stretch",
                },
                {
                    title: is-cn ? "标签" : "Tag",
                    key: "Tag",
                },
                {
                    title: is-cn ? "加载" : "Loading",
                    key: "Loading",
                },
                {
                    title: is-cn ? "弹出动作列表" : "PopupAction",
                    key: "PopupAction",
                },
                {
                    title: is-cn ? "横幅" : "Banner",
                    key: "Banner",
                },
                {
                    title: is-cn ? "链接" : "Link",
                    key: "Link",
                },
                {
                    title: is-cn ? "头像" : "Avatar",
                    key: "Avatar",
                },
                {
                    title: is-cn ? "空页面" : "Empty",
                    key: "Empty",
                },
                {
                    title: is-cn ? "列表条目" : "ListTile",
                    key: "ListTile",
                },
                {
                    title: is-cn ? "新闻" : "News",
                    key: "News",
                },
                {
                    title: is-cn ? "段落" : "Paragraph",
                    key: "Paragraph",
                },
                {
                    title: is-cn ? "代办列表" : "TodoList",
                    key: "TodoList",
                },
                {
                    title: is-cn ? "条形图" : "ChartBar",
                    key: "ChartBar",
                },
            ]
        },
        // Crypto
        {
            category: is-cn ? "加密类" : "Crypto",
            children: [
                {
                    title: is-cn ? "组记词" : "Mnemonic",
                    key: "Mnemonic",
                },
                {
                    title: is-cn ? "地址簿" : "AddressBook",
                    key: "AddressBook",
                },
                {
                    title: is-cn ? "账户余额" : "AccountBalance",
                    key: "AccountBalance",
                },
                {
                    title: is-cn ? "代币列表" : "TokenList",
                    key: "TokenList",
                },
                {
                    title: is-cn ? "代币发送" : "TokenSender",
                    key: "TokenSender",
                },
                {
                    title: is-cn ? "代币接收" : "TokenRecipient",
                    key: "TokenRecipient",
                },
                {
                    title: is-cn ? "交易费用" : "TransactionFee",
                    key: "TransactionFee",
                },
                {
                    title: is-cn ? "等待交易确认" : "WaitTransactionConfirmed",
                    key: "WaitTransactionConfirmed",
                },
                {
                    title: is-cn ? "交易历史" : "TransactionTile",
                    key: "TransactionTile",
                },
            ]
        },
        // MultiMedia
        {
            category: is-cn ? "多媒体" : "MultiMedia",
            is-open: false,
            children: [
                {
                    title: is-cn ? "音乐控制" : "AudioControl",
                    key: "AudioControl",
                },
                {
                    title: is-cn ? "视频控制" : "VideoControl",
                    key: "VideoControl",
                },
            ]
        },
        // Other
        {
            category: is-cn ? "其他类" : "Other",
            children: [
                {
                    title: is-cn ? "关于" : "About",
                    key: "About",
                },
                {
                    title: is-cn ? "设置" : "Setting",
                    key: "Setting",
                },
                {
                    title: is-cn ? "弹框" : "Dialog",
                    key: "Dialog",
                },
                {
                    title: is-cn ? "欢迎页面" : "LandingPage",
                    key: "LandingPage",
                },
                {
                    title: is-cn ? "品牌" : "Brand",
                    key: "Brand",
                },
                {
                    title: is-cn ? "帮助" : "Help",
                    key: "Help",
                },
            ]
        },
    ];

    //////////////////////////////// Logic End  ////////////////////////////////
}
