import { Util } from "util.slint";
import { Logic } from "logic.slint";
import { Theme, Icons } from "theme.slint";
import { Store,  DeviceType  } from "store.slint";

import { WebPanel } from "panel/web/panel.slint";
import { LoadingStatus, Toast, ConfirmDialog, ConfirmDialogSetting, Blanket, ToastSetting, ToastStatus, PopupActionSetting } from "base/widgets.slint";

export component AppWindow inherits Window {
    default-font-weight: Theme.normal-font-weight;
    background: Theme.base-background;

    WebPanel { }

    if ConfirmDialogSetting.show: Blanket {
        clicked => {
            ConfirmDialogSetting.show = false;
        }
    }

    if ConfirmDialogSetting.show: ConfirmDialog {
        is-prevent-event-forward: true;
        width: Math.min(root.width * 0.9, self.vbox-preferred-width * 2);
    }

    if !ToastSetting.is-timeout || ToastSetting.is-hover: Toast {
        x: root.width / 2 - self.width / 2;
        y: 50px;
        inner-max-width: root.width * 80%;
        clicked => {
            Logic.copy-to-clipboard(ToastSetting.text);
        }
    }
}

export {
    Util, Logic, Store, Theme, Icons, LoadingStatus, ToastSetting, ToastStatus, DeviceType, PopupActionSetting
    }
