import { Theme, Icons } from "theme.slint";
import { Label } from "label.slint";
import { IconBtn } from "icon-btn.slint";

// Example:
// BlankWelcome {
//     title: "Welcome to use slint-template";
//        sub-title: "It's a template project for slint GUI framework";
// }
export component BlankWelcome inherits HorizontalLayout {
    in-out property <string> title;
    in-out property <string> sub-title;
    in-out property <color> text-color: Theme.primary-text-color;
    in-out property <float> title-opacity: Theme.blank-welcome-opacity;
    in-out property <float> sub-title-opacity: Theme.blank-welcome-opacity;
    in-out property <float> img-opacity: Theme.blank-welcome-opacity;

    padding: Theme.padding * 2;
    padding-top: Theme.padding * 8;

    VerticalLayout {
        alignment: LayoutAlignment.center;
        spacing: Theme.spacing * 2;

        Label {
            text: title;
            font-size: Theme.title1-font-size + 10px;
            font-weight: Theme.bold-font-weight;
            horizontal-alignment: TextHorizontalAlignment.center;
            opacity: root.title-opacity;
            color: root.text-color;
        }

        Label {
            text: sub-title;
            font-size: Theme.title4-font-size;
            font-weight: Theme.bold-font-weight;
            horizontal-alignment: TextHorizontalAlignment.center;
            opacity: root.sub-title-opacity;
            color: root.text-color;
        }

        HorizontalLayout {
            alignment: center;
            padding-top: Theme.padding * 4;

            Image {
                width: Math.min(root.width * 0.8, self.preferred-width);
                source: Icons.brand;
                opacity: root.img-opacity;
            }
        }
    }
}
