import { Theme, Icons } from "../theme.slint";
import { Label } from "label.slint";
import { IconBtn } from "icon-btn.slint";

// Example:
// BlankWelcome {
//     title: "Welcome to use slint-template";
//        sub-title: "It's a template project for slint GUI framework";
// }
export component BlankWelcome inherits HorizontalLayout {
    in-out property <string> title;
    in-out property <string> sub-title;

    padding: Theme.padding * 2;
    padding-top: Theme.padding * 8;
    opacity: Theme.blank-welcome-opacity;

    VerticalLayout {
        alignment: LayoutAlignment.center;
        spacing: Theme.spacing * 2;

        Label {
            text: title;
            font-size: Theme.title1-font-size + 10px;
            font-weight: Theme.bold-font-weight;
            horizontal-alignment: TextHorizontalAlignment.center;
        }

        Label {
            text: sub-title;
            font-size: Theme.title3-font-size;
            font-weight: Theme.bold-font-weight;
            horizontal-alignment: TextHorizontalAlignment.center;
        }

        HorizontalLayout {
            alignment: center;
            padding-top: Theme.padding * 4;

            Image {
                width: Math.min(root.width * 0.8, self.preferred-width);
                source: Icons.brand;
            }
        }
    }
}
