import { Theme, Icons } from "../theme.slint";
import { IconBtn } from "./icon-btn.slint";
import { Divider } from "./divider.slint";

export component Head inherits Rectangle {
    height: hbox.preferred-height;
    background: Theme.base-background;

    in-out property <bool> is-show-divider;
    in-out property <string> title;

    in-out property icon <=> ic.icon;
    in-out property icon-size <=> ic.icon-size;
    in-out property icon-colorize <=> ic.colorize;

    in-out property <LayoutAlignment> hbox-alignment: LayoutAlignment.stretch;
    in-out property <length> hpadding: Theme.padding;
    in-out property <length> vpadding: Theme.padding;

    callback clicked <=> ic.clicked;

    hbox := HorizontalLayout {
        alignment: hbox-alignment;
        padding-left: root.hpadding;
        padding-right: root.hpadding;
        padding-top: root.vpadding;
        padding-bottom: root.vpadding;

        ic := IconBtn {
            icon-size: Theme.icon-size;
            background: Colors.transparent;
            icon: Icons.back;
            text: root.title;
        }

        @children
    }

    if is-show-divider : Divider {
        x: 0;
        y: root.height - self.height;
        background: Theme.base-border-color;
    }
}
