import { Theme, Icons } from "theme.slint";
import { Label } from "./label.slint";
import { IconBtn } from "./icon-btn.slint";

// Example:
// LineInput {
//     placeholder-text: Logic.tr("keyword");
//     icon: Icons.paste;
//     icon-colorize: Theme.icon-color;
//     is-show-icon: true;

//     // catch special keys, likes: Ctrl + A
//     key-pressed(event) => {
//         debug(event.text);
//     }

//     clicked => {
//         debug("clicked");
//     }

//     edited => {
//     }
//     accepted => {
//     }
// }

export component LineInput inherits Rectangle {
    in-out property text <=> text-input.text;
    in-out property font-size <=> text-input.font-size;
    in-out property font-weight <=> text-input.font-weight;
    in-out property text-color <=> text-input.color;
    in property input-type <=> text-input.input-type;
    in property read-only <=> text-input.read-only;
    in property <bool> enabled <=> text-input.enabled;
    in-out property <string> placeholder-text;
    in-out property placeholder <=> self.placeholder-text;
    in-out property <color> disabled-color: Theme.disabled-color;
    in-out property <bool> gain-focus-when-clicked: true;
    in-out property <color> placeholder-text-color: Theme.placeholder-text-color;
    out property has-focus <=> text-input.has-focus;
    out property <color> default-border-color: (text-input.has-focus && self.enabled && !read-only) ? Theme.thirdly-brand-color : Theme.base-border-color;
    in-out property <bool> show-icon-hover-background: true;
    in-out property <bool> is-show-color-block;
    in-out property <color> color-block-color;

    in-out property <bool> enable-step: true;
    in-out property <int> number-step: 1;
    in-out property <float> decimal-step: 0.1;

    in property <bool> is-show-icon;
    in property <image> icon;
    in property <color> icon-colorize: Theme.icon-color;
    in property <length> icon-size: Theme.icon-size;

    in property <length> hpadding: Theme.padding * 2;
    in property <length> vpadding: Theme.padding * 2;

    callback clicked();
    callback accepted();
    callback edited <=> text-input.edited;
    callback key-pressed(key-event: KeyEvent);

    preferred-width: 300px;
    preferred-height: hbox.preferred-height;

    forward-focus: text-input;
    border-radius: Theme.border-radius;
    border-width: text-input.has-focus ? 2px : 1px;
    border-color: default-border-color;

    public function paste() {
        text-input.paste();
    }

    public function copy() {
        text-input.copy();
    }

    hbox := HorizontalLayout {
        spacing: Theme.spacing * 2;
        padding-left: root.hpadding;
        padding-right: root.hpadding;
        padding-top: root.vpadding;
        padding-bottom: root.vpadding;

        Flickable {
            viewport-width: text-input.preferred-width + Theme.padding;
            height: text-input.preferred-height;

            Rectangle {
                x: 0;
                width: Math.max(parent.width, text-input.preferred-width);

                if root.enabled && root.enable-step && !text-input.text.is-empty && text-input.has-focus && (text-input.input-type == InputType.number || text-input.input-type == InputType.decimal): TouchArea {
                    enabled: root.enabled;

                    scroll-event(event) => {
                        if (event.delta-y < 0) {
                            if (text-input.input-type == InputType.number) {
                                text-input.text = (text-input.text.to-float() + root.number-step).round();
                            } else if (text-input.input-type == InputType.decimal) {
                                text-input.text = (text-input.text.to-float() + root.decimal-step);
                            }
                        } else if (event.delta-y > 0) {
                            if (text-input.input-type == InputType.number) {
                                text-input.text = (text-input.text.to-float() - root.number-step).round();
                            } else if (text-input.input-type == InputType.decimal) {
                                text-input.text = (text-input.text.to-float() - root.decimal-step);
                            }
                        }
                        accept
                    }
                }

                fs := FocusScope {
                    key-pressed(event) => {
                        if (event.text == Key.Escape) {
                            fs.focus();
                        }
                        root.key-pressed(event);
                        accept
                    }

                    HorizontalLayout {
                        spacing: Theme.spacing * 2;

                        if is-show-color-block: VerticalLayout {
                            alignment: center;
                            private property <bool> is-transcparent: text-input.text == "#00000000";

                            if is-transcparent: Image {
                                width: text-input.font-size * 0.8;
                                height: self.width;
                                source: Icons.transparent-light;
                            }

                            if !is-transcparent: Rectangle {
                                width: text-input.font-size * 0.8;
                                height: self.width;
                                background: color-block-color;
                            }
                        }

                        text-input := TextInput {
                            single-line: true;
                            vertical-alignment: TextVerticalAlignment.center;
                            color: root.enabled ? Theme.primary-text-color : root.disabled-color;
                            font-size: Theme.default-font-size;

                            accepted => {
                                self.clear-focus();
                                root.accepted();
                            }
                        }
                    }
                }

                if text-input.text == "": Label {
                    x: 0;
                    text: root.placeholder-text;
                    color: root.enabled ? root.placeholder-text-color : root.disabled-color;
                    font-size: text-input.font-size - 2px;
                }

                TouchArea {
                    enabled: root.enabled && text-input.text.is-empty;
                    mouse-cursor: MouseCursor.text;

                    clicked => {
                        text-input.focus();
                    }
                }
            }
        }

        if root.is-show-icon: VerticalLayout {
            alignment: LayoutAlignment.center;

            IconBtn {
                enabled: root.enabled;
                width: root.icon-size;
                height: self.width;
                icon: root.icon;
                icon-size: root.icon-size;
                colorize: root.icon-colorize;
                gain-focus-when-clicked: gain-focus-when-clicked;
                show-icon-hover-background: root.show-icon-hover-background;

                clicked => {
                    root.clicked();
                }
            }
        }
    }
}

export component ClickAndEditLabel inherits Rectangle {
    in-out property <string> text;
    in-out property <bool> is-edit;
    in-out property <bool> use-fixed-width;
    in-out property <bool> allow-breaking-text-binding-when-edit;
    in-out property <bool> show-icon-hover-background: true;
    in-out property <int> font-weight: Theme.normal-font-weight;
    in-out property <length> font-size: Theme.default-font-size;
    in-out property <color> text-color: Theme.regular-text-color;
    in-out property <bool> disabled-click-enter-edit-mode;
    in-out property <bool> enabled-double-click-enter-edit-mode;
    in-out property wrap <=> lb.wrap;
    in-out property enabled <=> lb.enabled;
    in-out property overflow <=> lb.overflow;
    in-out property vpadding <=> li.vpadding;
    out property has-focus <=> li.has-focus;

    private property <bool> inner-is-edit;

    callback accepted(text: string);
    callback edited(text: string);
    callback clicked();
    callback double-clicked();
    callback escape();

    changed text => {
        li.text = text;
    }

    changed is-edit => {
        if (is-edit) {
            inner-is-edit = true;
        } else {
            inner-is-edit = false;
        }
    }

    public function enter-edit-mode() {
        if (disabled-click-enter-edit-mode) {
            inner-is-edit = true;
            li.focus();
        }
    }

    width: lb.preferred-width;

    VerticalLayout {
        visible: !inner-is-edit;
        alignment: center;

        changed visible => {
            if (!use-fixed-width && self.visible) {
                root.width = lb.preferred-width;
            }
            if (self.visible) {
                li.text = root.text;
            }
        }

        lb := Label {
            text: root.text;
            font-size: root.font-size;
            font-weight: root.font-weight;
            color: root.text-color;

            TouchArea {
                enabled: root.enabled && !disabled-click-enter-edit-mode;
                mouse-cursor: MouseCursor.pointer;

                function enter-edit-mode() {
                    inner-is-edit = true;

                    if (inner-is-edit) {
                        li.focus();
                    }
                }

                clicked => {
                    if (!enabled-double-click-enter-edit-mode) {
                        enter-edit-mode();
                    }
                    root.clicked();
                }

                double-clicked => {
                    if (enabled-double-click-enter-edit-mode) {
                        enter-edit-mode();
                    }
                    root.double-clicked();
                }
            }
        }
    }

    VerticalLayout {
        visible: inner-is-edit;
        alignment: center;

        changed visible => {
            if (!use-fixed-width && self.visible) {
                root.width = li.width;
            }
        }

        li := LineInput {
            enabled: root.enabled;
            width: use-fixed-width ? root.width : lb.preferred-width + self.hpadding * 2;
            text: root.text;
            font-size: root.font-size;
            font-weight: root.font-weight;
            text-color: root.text-color;
            show-icon-hover-background: root.show-icon-hover-background;

            accepted => {
                inner-is-edit = !inner-is-edit;
                root.accepted(self.text);
            }

            edited => {
                if (allow-breaking-text-binding-when-edit) {
                    root.text = self.text;
                }
                root.edited(self.text);
            }

            key-pressed(key-event) => {
                if (key-event.text == Key.Escape) {
                    inner-is-edit = false;
                    root.escape();
                }
            }
        }
    }
}
