import { Theme, Icons } from "theme.slint";
import { DialogStatusBar } from "status-bar.slint";
import { SettingDetailInner } from "setting-detail.slint";

export component MovingDialog inherits Rectangle {
    private property <bool> show-body: true;
    in-out property title <=> sb.title;
    in-out property header-width <=> sb.width;
    in-out property body-height <=> vbox.preferred-height;
    in-out property icon <=> sb.icon;
    in-out property <length> head-x <=> sb.x;
    in-out property <length> head-y <=> sb.y;
    in-out property <bool> enable-resize;
    in-out property <length> body-border-width: Theme.default-border-width * 2;
    in-out property <color> content-background: Theme.base-background;
    in-out property <bool> always-show-resize-area: true;
    in-out property <length> min-header-width: Theme.moving-dialog-min-width;
    in-out property <length> min-body-height: Theme.moving-dialog-min-height;

    private property <length> normal-header-width: max(header-width, root.min-header-width);

    callback close <=> sb.close;
    callback resize(offset-x: length, offset-y: length);
    callback minimal();
    callback maximal();

    init => {
        root.normal-header-width = root.header-width;
    }

    sb := DialogStatusBar {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height - body.height) / 2;
        width: Theme.default-font-size * 13;
        container-width: root.width;
        container-height: root.height;
        hide-maximal-ctrl-btns: root.show-body;
        hide-minimal-ctrl-btns: !root.show-body;

        maximal => {
            root.header-width = root.normal-header-width;
            root.show-body = !root.show-body;
            root.maximal();
        }

        minimal => {
            root.header-width = sb.minimal-bar-width;
            root.show-body = !root.show-body;
            head-x = head-x.max(0);
            head-y = head-y.max(0);
            root.minimal();
        }
    }

    body := SettingDetailInner {
        visible: root.show-body;
        x: sb.x;
        y: sb.y + sb.height - 1px;
        width: sb.width;
        height: self.width / Theme.golden-ratio - sb.height;
        vbox-padding: 0px;
        interactive: false;

        Rectangle {
            width: parent.width;
            background: root.content-background;
            border-width: root.body-border-width;
            border-color: Theme.base-border-color;
            height: vbox.preferred-height;

            TouchArea { }

            vbox := VerticalLayout {
                padding: parent.border-width;
                @children
            }

            if enable-resize: Rectangle {
                x: parent.width - self.width - root.body-border-width;
                y: parent.height - self.height - root.body-border-width;
                width: Theme.padding * 3;
                height: self.width;

                Path {
                    x: 0;
                    y: 0;
                    width: parent.width;
                    height: parent.height;
                    fill: always-show-resize-area || resize-ta.has-hover ? Theme.regular-text-color : transparent;

                    MoveTo {
                        x: 0;
                        y: parent.height / 1px;
                    }

                    LineTo {
                        x: parent.width / 1px;
                        y: parent.height / 1px;
                    }

                    LineTo {
                        x: parent.width / 1px;
                        y: 0;
                    }

                    Close { }
                }

                resize-ta := TouchArea {
                    mouse-cursor: MouseCursor.se-resize;

                    moved => {
                        let offset-x = self.mouse-x - self.pressed-x;
                        let offset-y = self.mouse-y - self.pressed-y;
                        root.header-width = max(root.header-width + offset-x, root.min-header-width);
                        root.body-height = max(root.body-height + offset-y, root.min-body-height);
                        root.normal-header-width = root.header-width;
                        root.resize(offset-x, offset-y);
                    }
                }
            }
        }
    }
}
