import { Theme, Icons } from "theme.slint";
import { SettingDetailInner } from "setting-detail.slint";
import { DialogStatusBar } from "status-bar.slint";

export component MovingDialog inherits Rectangle {
    private property <bool> show-body: true;
    in-out property title <=> sb.title;
    in-out property header-width <=> sb.width;
    in-out property icon <=> sb.icon;
    in-out property <length> head-x <=> sb.x;
    in-out property <length> head-y <=> sb.y;
    in-out property <bool> enable-resize;
    in-out property <length> body-border-width: Theme.default-border-width * 2;
    in-out property <color> content-background: Theme.base-background;

    callback close <=> sb.close;
    callback resize(offset: length);

    sb := DialogStatusBar {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height - body.height) / 2;
        width: Theme.default-font-size * 13;
        container-width: root.width;
        container-height: root.height;
        hide-maximal-ctrl-btns: root.show-body;
        hide-minimal-ctrl-btns: !root.show-body;

        maximal => {
            root.show-body = !root.show-body;
        }

        minimal => {
            root.show-body = !root.show-body;
        }
    }

    body := SettingDetailInner {
        visible: root.show-body;
        x: sb.x;
        y: sb.y + sb.height;
        width: sb.width;
        height: self.width / Theme.golden-ratio - sb.height;
        vbox-padding: 0px;
        interactive: false;

        Rectangle {
            width: parent.width;
            background: root.content-background;
            border-width: root.body-border-width;
            border-color: Theme.base-border-color;
            height: vbox.preferred-height;

            vbox := VerticalLayout {
                padding: parent.border-width;
                @children
            }

            if enable-resize: Rectangle {
                x: parent.width - self.width;
                y: parent.height - self.height;
                width: Theme.padding * 3;
                height: self.width;
                background: resize-ta.has-hover ? Theme.thirdly-brand-color : transparent;

                resize-ta := TouchArea {
                    mouse-cursor: MouseCursor.se-resize;

                    moved => {
                        root.resize(self.mouse-x - self.pressed-x);
                    }
                }
            }
        }
    }
}
