import { Theme, Icons } from "theme.slint";
import { CenterLayout } from "./center-layout.slint";

export component NoDataImg inherits Rectangle {
    in-out property <string> text;
    in-out property <length> font-size: Theme.default-font-size + 4px;
    in-out property <color> font-color: Theme.primary-text-color;
    in-out property img-width <=> img.width;
    in-out property image <=> img.source;
    in-out property colorize <=> img.colorize;

    width: 300px;
    opacity: 0.5;

    CenterLayout {
        CenterLayout {
            img := Image {
                width: root.width * 0.6;
                source: Icons.no-data-fill;
            }
        }

        if !root.text.is-empty: CenterLayout {
            Text {
                text: root.text;
                color: root.font-color;
                font-size: root.font-size;
            }
        }
    }
}
