import { Theme, Icons } from "../theme.slint";
import { CenterLayout } from "./center-layout.slint";

export component NoMessageImg inherits Rectangle {
    in-out property img-width <=> img.width;
    in-out property <string> text;
    width: 300px;

    opacity: 0.5;

    CenterLayout {
        CenterLayout {
            img := Image {
                width: root.width * 0.6;
                source: Icons.no-message;
            }
        }

        CenterLayout {
            if !root.text.is-empty: Text {
                color: Theme.primary-text-color;
                font-size: Theme.default-font-size + 4px;
                text: root.text;
            }

            @children
        }
    }
}
