import { Theme, Icons } from "../theme.slint";
import { IconBtn } from "icon-btn.slint";

export component Rate inherits HorizontalLayout {
    in-out property <int> count: 5;
    in-out property <int> rate: 3;
    in-out property <length> icon-size: Theme.icon-size;

    alignment: LayoutAlignment.start;

    private property <int> cache-rate;

    for index in count: IconBtn {
        icon: Icons.star-round;
        icon-size: icon-size;
        colorize: index < rate ? Theme.mark-color : Theme.unmark-color;
        use-auto-size: true;
        auto-size-hpadding: Theme.padding;

        clicked => {
            cache-rate = index + 1;
        }

        entered => {
            cache-rate = root.rate;
            rate = index + 1;
        }

        leave => {
            rate = root.cache-rate;
        }
    }
}
