import { Theme } from "theme.slint";
import { Util } from "util.slint";
import { Label } from "label.slint";
import { Divider } from "divider.slint";

export component ReadonlySoundWaveForm inherits Rectangle {
    in-out property <[float]> data;
    in-out property <bool> is-mono;
    in-out property <bool> show-center-line;
    in-out property <color> center-line-color: Theme.divider-color;
    in-out property <color> sample-color: Theme.divider-color;
    in-out property <float> amplitude-scale: 1.0;

    if is-mono: Rectangle {
        private property <length> sample-width: root.width / max(1, root.data.length);

        for index in root.data.length: Rectangle {
            x: index * parent.sample-width;
            y: root.height * (1 - min(1.0, abs(root.data[index]) * root.amplitude-scale));
            width: max(parent.sample-width, 1px);
            height: root.height * min(1.0, abs(root.data[index]) * root.amplitude-scale);
            background: root.sample-color;
        }
    }

    if !is-mono: Rectangle {
        private property <length> sample-width: root.width / max(1, root.data.length / 2);

        for index in root.data.length / 2: Rectangle {
            private property <float> left-value: min(1.0, abs(root.data[index * 2]) * root.amplitude-scale);
            private property <float> right-value: min(1.0, abs(root.data[index * 2 + 1]) * root.amplitude-scale);

            x: index * parent.sample-width;
            width: max(parent.sample-width, 1px);

            Rectangle {
                y: root.height / 2 - self.height;
                height: root.height * left-value / 2;
                background: root.sample-color;
            }

            Rectangle {
                y: root.height / 2;
                height: root.height * right-value / 2;
                background: root.sample-color;
            }
        }
    }

    if show-center-line: Divider {
        width: 100%;
        background: root.center-line-color;
    }
}
