import { Logic } from "../logic.slint";
import { Theme, Icons } from "theme.slint";
import { Label } from "label.slint";
import { CancelBtn, ConfirmBtn } from "btn.slint";

export component RecoveryDialog inherits Rectangle {
    height: vbox.preferred-height;
    width: self.preferred-width / Theme.golden-ratio;
    preferred-width: vbox.preferred-width;
    background: Theme.base-background;
    border-radius: Theme.border-radius;
    border-width: Theme.default-border-width;
    border-color: Theme.base-border-color;

    in-out property <bool> is-prevent-event-forward: false;
    in-out property vbox-preferred-width <=> vbox.preferred-width;
    in-out property tip-text <=> tip-lb.text;
    in-out property <string> save-time;

    callback recovered <=> recover-btn.clicked;
    callback ignored <=> ignore-btn.clicked;
    callback cancelled <=> cancel-btn.clicked;

    if is-prevent-event-forward: TouchArea { }

    vbox := VerticalLayout {
        alignment: start;
        padding: Theme.padding * 4;
        spacing: Theme.spacing * 4;

        title-label := Label {
            text: Logic.tr("Recovery Available");
            color: Theme.primary-text-color;
            font-size: Theme.title1-font-size;
        }

        tip-lb := Label {
            wrap: word-wrap;
            color: Theme.secondary-text-color;
            font-size: Theme.title4-font-size;
            text: Logic.tr("A recovery file was found. Would you like to restore from it?");
        }

        if !save-time.is-empty: Label {
            wrap: word-wrap;
            horizontal-alignment: TextHorizontalAlignment.right;
            color: Theme.secondary-text-color;
            font-size: Theme.title5-font-size;
            text: save-time;
        }

        HorizontalLayout {
            alignment: end;
            spacing: Theme.spacing * 4;

            cancel-btn := CancelBtn {
                text: Logic.tr("Cancel");
            }

            ignore-btn := CancelBtn {
                text: Logic.tr("Ignore");
                icon: Icons.ignore-light;
            }

            recover-btn := ConfirmBtn {
                text: Logic.tr("Recover");
                icon: Icons.recover-light;
            }
        }
    }
}
