import { Theme, Icons } from "theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Dialog } from "./dialog.slint";
import { LineInput } from "line-input.slint";
import { Label } from "label.slint";
import { DialogStatusBar } from "status-bar.slint";

export component ReplaceDialog inherits Rectangle {
    private property <length> header-width: Math.min(Theme.dialog-max-width, Theme.default-font-size * 25);

    callback escape();
    callback replace(old-text: string, new-text: string);

    init => {
        old-line-input.focus();
    }

    sb := DialogStatusBar {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height - body.height) / 2;
        width: header-width - root.border-width * 2;
        icon: Icons.replace-light;
        title: Logic.tr("Replace");
        container-width: root.width;
        container-height: root.height;

        close => {
            escape();
        }
    }

    body := Rectangle {
        x: sb.x;
        y: sb.y + sb.height;
        width: header-width;
        height: vbox.preferred-height + self.border-width * 2;
        border-width: Theme.default-border-width;
        border-color: Theme.base-border-color;
        background: Theme.base-background;

        vbox := VerticalLayout {
            spacing: Theme.spacing * 2;
            padding: Theme.spacing * 2;
            padding-top: 0;
            alignment: start;

            VerticalLayout {
                spacing: Theme.spacing;

                Label {
                    text: Logic.tr("Replaced text");
                }

                old-line-input := LineInput {
                    is-show-icon: true;
                    icon: Icons.close-light;
                    icon-size: Theme.icon-size * Theme.golden-ratio;
                    gain-focus-when-clicked: false;

                    key-pressed(event) => {
                        if (event.text == Key.Tab) {
                            new-line-input.focus();
                        }
                    }

                    clicked => {
                        self.text = "";
                    }

                    accepted => {
                        self.focus();
                    }
                }
            }

            VerticalLayout {
                spacing: Theme.spacing;
                Label {
                    text: Logic.tr("Target text");
                }

                new-line-input := LineInput {
                    is-show-icon: true;
                    icon: Icons.close-light;
                    icon-size: Theme.icon-size * Theme.golden-ratio;
                    gain-focus-when-clicked: false;

                    key-pressed(event) => {
                        if (event.text == Key.Tab) {
                            old-line-input.focus();
                        }
                    }

                    clicked => {
                        self.text = "";
                    }

                    accepted => {
                        replace(old-line-input.text, new-line-input.text);
                        self.focus();
                    }
                }
            }
        }
    }
}
