import { Theme } from "theme.slint";
import { Util } from "../panel/def.slint";
import { Label } from "label.slint";

// Example:
// SoundWaveForm {
//     width: Math.min(1000px, root.width * 0.8);
//     wave-data: noise-data;
//     wave-color: Theme.warning-color;
//     show-timestamp: true;
//     start-timestamp: "01:00";
//     end-timestamp: "05:00";
// }

export component SoundWaveForm inherits Rectangle {
    in-out property <[float]> wave-data;
    in-out property <float> zoom-level: 1.0;
    in-out property <float> amplitude-scale: 1.0;
    in-out property <length> data-width: 2px;
    in-out property <color> wave-color: Theme.brand-color;
    in-out property <bool> is-mono;
    in-out property <bool> show-control-handle: true;
    in-out property <color> start-control-handle-color: Theme.success-color;
    in-out property <color> end-control-handle-color: Theme.danger-color;
    in-out property <length> control-handle-size: Theme.icon-size * 0.8;
    in-out property <string> start-timestamp: "00:00";
    in-out property <string> end-timestamp: "00:00";
    in-out property <color> timestamp-color: Theme.regular-text-color;
    in-out property <bool> show-timestamp;

    in-out property center-line-color <=> center-line.background;

    private property <length> max-data-width: 16px;
    private property <length> horizontal-offset: 0px;
    private property <length> start-control-handle-pos-cache: control-handle-size / -2;
    private property <length> end-control-handle-pos-cache: root.width - control-handle-size / 2;
    private property <[float]> final-wave-data: Util.cal-sound-wave(root.wave-data, clamp(root.width / 1px, 1, max-data-width / 1px), root.data-width / 1px, self.is-mono);

    callback move(percent: float); // move left: < 0; move right: > 0;
    callback zoom-changed(level: float);
    callback amplitude-changed(scale: float);
    callback start-position-changed(position: float); // [0, 1]
    callback end-position-changed(position: float); // [0, 1]

    public function reset-view() {
        zoom-level = 1.0;
        amplitude-scale = 1.0;
        horizontal-offset = 0px;
    }

    width: wave-data.length * 2px;
    height: Theme.default-font-size * 10;
    background: Theme.secondary-background;
    border-width: Theme.default-border-width;
    border-color: Theme.base-border-color;
    border-radius: Theme.border-radius;

    Rectangle {
        clip: true;

        if is-mono: Rectangle {
            for data-index in final-wave-data.length: Rectangle {
                x: (data-index / Math.max(1, final-wave-data.length)) * parent.width * zoom-level + horizontal-offset;
                y: final-wave-data[data-index] >= 0 ? (parent.height / 2 - self.height) : (parent.height / 2);
                width: Math.clamp((parent.width * zoom-level / Math.max(1, final-wave-data.length)), 1px, max-data-width);
                height: Math.abs(final-wave-data[data-index]) * parent.height / 2 * amplitude-scale;
                background: wave-color;
            }
        }

        if !is-mono: Rectangle {
            private property <int> frame-counts: final-wave-data.length / 2;

            for data-index in frame_counts: Rectangle {
                Rectangle {
                    x: (data-index / Math.max(1, frame-counts)) * parent.width * zoom-level + horizontal-offset;
                    y: final-wave-data[data-index] >= 0 ? (parent.height / 2 - self.height) : (parent.height / 2);
                    width: Math.clamp((parent.width * zoom-level / Math.max(1, frame-counts)), 1px, max-data-width);
                    height: Math.abs(final-wave-data[data-index + 1]) * parent.height / 2 * amplitude-scale;
                    background: wave-color;
                }

                Rectangle {
                    x: (data-index / Math.max(1, frame-counts)) * parent.width * zoom-level + horizontal-offset;
                    y: final-wave-data[data-index + 1] >= 0 ? (parent.height / 2 - self.height) : (parent.height / 2);
                    width: Math.clamp((parent.width * zoom-level / Math.max(1, frame-counts)), 1px, max-data-width);
                    height: Math.abs(final-wave-data[data-index + 1]) * parent.height / 2 * amplitude-scale;
                    background: wave-color;
                }
            }
        }
    }

    HorizontalLayout {
        padding-left: show-timestamp ? Theme.padding : 0;
        padding-right: show-timestamp ? Theme.padding : 0;
        alignment: space-between;
        width: root.width;

        private property <length> start-timestamp-lable-width;
        private property <length> end-timestamp-lable-width;

        if show-timestamp: Label {
            init => {
                start-timestamp-lable-width = self.preferred-width;
            }

            text: start-timestamp;
            color: timestamp-color;
        }

        center-line := Rectangle {
            y: parent.height / 2 - self.height / 2;
            width: !show-timestamp ? root.width : root.width - start-timestamp-lable-width - end-timestamp-lable-width - parent.padding-left - parent.padding-right - Theme.padding * 2;
            height: Theme.default-border-width;
            background: Theme.have-read-text-color;
        }

        if show-timestamp: Label {
            init => {
                end-timestamp-lable-width = self.preferred-width;
            }

            text: end-timestamp;
            color: timestamp-color;
        }
    }

    TouchArea {
        mouse-cursor: self.pressed ? MouseCursor.grabbing : MouseCursor.grab;

        property <length> start-drag-x: 0px;
        property <length> start-offset: 0px;
        property <bool> is-dragging: false;

        clicked => {
            is-dragging = false;
            move((self.mouse-x - start-drag-x) / root.width);
        }

        moved => {
            if (self.pressed) {
                if (!is-dragging) {
                    start-offset = horizontal-offset;
                    start-drag-x = self.mouse-x;
                    is-dragging = true;
                }
                let delta-x = start-drag-x - self.mouse-x;
                horizontal-offset = start-offset - delta-x;
            }
        }

        scroll-event(event) => {
            if (event.modifiers.control) {
                if (event.delta-y > 0) {
                    amplitude-scale += 0.1;
                    amplitude-changed(amplitude-scale);
                    return EventResult.accept;
                } else if (event.delta-y < 0) {
                    amplitude-scale = max(0,  amplitude-scale - 0.1);
                    amplitude-changed(amplitude-scale);
                    return EventResult.accept;
                }
            } else {

                if (event.delta-y > 0) {
                    zoom-level += 0.1;
                    zoom-changed(zoom-level);
                    return EventResult.accept;
                } else if (event.delta-y < 0) {
                    zoom-level = max(0, zoom-level - 0.1);
                    zoom-changed(zoom-level);
                    return EventResult.accept;
                }
            }
            return EventResult.reject;
        }
    }

    if show-control-handle: Rectangle {
        x: control-handle-size / -2;
        y: control-handle-size / -2;
        width: control-handle-size;
        height: root.height;

        start-rec := Rectangle {
            y: 0;
            width: control-handle-size;
            height: self.width;
            border-radius: self.width / 2;
            background: start-control-handle-color;
        }

        Rectangle {
            x: start-rec.x + control-handle-size / 2;
            y: control-handle-size / 2;
            width: Theme.default-border-width * 2;
            height: root.height;
            background: start-control-handle-color;
        }

        TouchArea {
            mouse-cursor: MouseCursor.move;

            moved => {
                if (self.pressed) {
                    parent.x = min( clamp(parent.x + self.mouse-x - self.pressed-x, - control-handle-size / 2, root.width - control-handle-size / 2), root.end-control-handle-pos-cache);

                    root.start-control-handle-pos-cache = parent.x;
                    start-position-changed((parent.x + control-handle-size) / root.width);
                }
            }
        }
    }

    if show-control-handle: Rectangle {
        x: root.width - control-handle-size / 2;
        y: control-handle-size / -2;
        width: control-handle-size;
        height: root.height;

        end-rec := Rectangle {
            y: 0;
            width: control-handle-size;
            height: self.width;
            border-radius: self.width / 2;
            background: end-control-handle-color;
        }

        Rectangle {
            x: end-rec.x + control-handle-size / 2;
            y: control-handle-size / 2;
            width: Theme.default-border-width * 2;
            height: root.height;
            background: end-control-handle-color;
        }

        TouchArea {
            mouse-cursor: MouseCursor.move;

            moved => {
                if (self.pressed) {
                    parent.x = max(clamp(parent.x + self.mouse-x - self.pressed-x, - control-handle-size / 2, root.width - control-handle-size / 2), root.start-control-handle-pos-cache);

                    root.end-control-handle-pos-cache = parent.x;
                    end-position-changed((parent.x + control-handle-size) / root.width);
                }
            }
        }
    }
}
