import { AppPosType } from "def.slint";
import { Theme, Icons } from "theme.slint";
import { Logic } from "../logic.slint";
import { Util } from "util.slint";
import { Label } from "label.slint";
import { IconBtn } from "icon-btn.slint";
import { ConfirmDialogSetting } from "confirm-dialog.slint";
import { ComponentPosition } from "def.slint";

export component StatusBar inherits Rectangle {
    in-out property <length> icon-size: Theme.default-font-size;
    in-out property <bool> show-icon-hover-background: false;

    in-out property <bool> disable-maximal: false;
    in-out property <bool> is-app-window-bar: true;
    in-out property <bool> disable-window-ctrl-btns;
    in-out property <bool> draggable: true;

    in-out property <bool> hide-maximal-ctrl-btns;
    in-out property <bool> hide-minimal-ctrl-btns;
    in-out property <bool> hide-close-ctrl-btns;

    in-out property <image> close-icon: Icons.status-bar-close-fill;
    in-out property <color> close-icon-colorize: Theme.danger-color;
    in-out property <image> maximal-icon: Icons.status-bar-max-fill;
    in-out property <color> maximal-icon-colorize: root.disable-maximal ? Theme.disabled-color : Theme.success-color;
    in-out property <image> minimal-icon: Icons.status-bar-min-fill;
    in-out property <color> minimal-icon-colorize: Theme.warning-color;

    private property <length> min-title-icon-width;
    private property <length> min-ctrl-btns-width;
    in-out property <length> minimal-bar-width: hbox.preferred-width;

    in-out property <bool> is-show-icon;
    in-out property <image> icon;
    in-out property <string> title;
    in-out property <color> icon-colorize: transparent;
    in-out property <color> title-text-color: Theme.secondary-text-color;

    in-out property <bool> is-show-tip: false;
    in-out property <ComponentPosition> tip-position: ComponentPosition.Bottom;

    in-out property <length> container-width;
    in-out property <length> container-height;

    private property <AppPosType> origin-pos;
    private property <length> offset-x;
    private property <length> offset-y;
    private property <bool> enable-move;

    callback maximal();
    callback minimal();
    callback close();
    callback start-moving();
    callback stop-moving();
    callback clicked();
    callback top-z();

    background: Theme.secondary-background;
    height: Theme.header-height;

    TouchArea {
        clicked => {
            root.clicked();
        }

        moved => {
            if (!root.draggable || !root.enable-move) {
                return;
            }
            if (root.is-app-window-bar) {
                root.origin-pos = Util.get-current-pos();
                root.offset-x = self.pressed-x - self.mouse-x;
                root.offset-y = self.pressed-y - self.mouse-y;

                Util.set-current-pos({
                    x: root.origin-pos.x - root.offset-x,
                    y: root.origin-pos.y - root.offset-y,
                });
            } else {
                root.offset-x = self.pressed-x - self.mouse-x;
                root.offset-y = self.pressed-y - self.mouse-y;
                root.x = Math.clamp(root.x - root.offset-x, 0 - root.width / 2, root.container-width - root.width / 2);
                root.y = Math.clamp(root.y - root.offset-y, 0 - root.height / 2, root.container-height - root.height / 2);
            }
        }

        pointer-event(event) => {
            if (event.button == PointerEventButton.left) {
                if (event.kind == PointerEventKind.down) {
                    root.top-z();

                    if (root.draggable) {
                        root.enable-move = true;
                        root.start-moving();
                    }
                } else {
                    if (root.draggable) {
                        root.enable-move = false;
                        root.stop-moving();
                    }
                }
            }
        }
    }

    hbox := HorizontalLayout {
        padding-left: Theme.padding * 2;
        padding-right: Theme.padding * 2;
        spacing: Theme.spacing * 4;
        alignment: root.is-show-icon ? LayoutAlignment.space-between : LayoutAlignment.end;

        if root.is-show-icon: HorizontalLayout {
            spacing: Theme.spacing;

            init => {
                root.min-title-icon-width = self.preferred-width;
            }

            Image {
                source: root.icon;
                width: Math.min(root.icon-size + Theme.padding, root.height);
                colorize: root.icon-colorize;
            }

            Label {
                text: root.title;
                color: root.title-text-color;
                font-size: root.icon-size;
            }
        }

        HorizontalLayout {
            alignment: LayoutAlignment.end;

            @children

            if !disable-window-ctrl-btns: HorizontalLayout {
                spacing: Theme.spacing * 2;

                init => {
                    root.min-ctrl-btns-width = self.preferred-width;
                }

                if !hide-minimal-ctrl-btns: IconBtn {
                    icon: root.minimal-icon;
                    icon-size: root.icon-size;
                    colorize: root.minimal-icon-colorize;
                    show-icon-hover-background: root.show-icon-hover-background;
                    is-show-tip: root.is-show-tip;
                    tip-position: root.tip-position;
                    tip: Logic.tr("minimal");

                    clicked => {
                        if (root.is-app-window-bar) {
                            Util.min-window(true);
                        } else {
                            root.top-z();
                            root.minimal();
                        }
                    }
                }

                if !hide-maximal-ctrl-btns: IconBtn {
                    enabled-toucharea: !root.disable-maximal;
                    icon: root.maximal-icon;
                    icon-size: root.icon-size;
                    colorize: root.maximal-icon-colorize;
                    show-icon-hover-background: root.show-icon-hover-background;
                    is-show-tip: root.is-show-tip;
                    tip-position: root.tip-position;
                    tip: Logic.tr("maximal");

                    clicked => {
                        if (root.is-app-window-bar) {
                            if (Util.get-is-max-window()) {
                                Util.max-window(false);
                                self.icon = Icons.status-bar-max-fill;
                                self.tip = Logic.tr("maximal");
                            } else {
                                Util.max-window(true);
                                self.icon = Icons.status-bar-normal-fill;
                                self.tip = Logic.tr("normal");
                            }
                        } else {
                            root.top-z();
                            root.maximal();
                        }
                    }
                }

                if !hide-close-ctrl-btns: IconBtn {
                    icon: root.close-icon;
                    icon-size: root.icon-size;
                    colorize: root.close-icon-colorize;
                    show-icon-hover-background: root.show-icon-hover-background;
                    is-show-tip: root.is-show-tip;
                    tip-position: root.tip-position;
                    tip: Logic.tr("close");

                    clicked => {
                        if (root.is-app-window-bar) {
                            ConfirmDialogSetting.set(true, Logic.tr("Warning"), Logic.tr("Quit application or not?"), "close-window", "");
                        } else {
                            root.close();
                        }
                    }
                }
            }
        }
    }
}

export component DialogStatusBar inherits StatusBar {
    width: Theme.default-font-size * 13;
    hide-minimal-ctrl-btns: true;
    hide-maximal-ctrl-btns: true;
    is-show-icon: true;
    is-app-window-bar: false;
    background: Theme.secondary-brand-color;
    icon-colorize: Theme.light-text-color;
    title-text-color: Theme.light-text-color;
    close-icon: Icons.close-light;
    close-icon-colorize: Theme.light-text-color;
    maximal-icon: Icons.maximal-light;
    minimal-icon: Icons.minimal-light;
    minimal-icon-colorize: Theme.light-text-color;
    maximal-icon-colorize: Theme.light-text-color;
}
