import { Theme } from "theme.slint";
import { TextBtn } from "btn.slint";

// Example:
// TabBtns {
//     items: [
//         { icon: Icons.cancel-fill, text: "Cancel" },
//         { icon: Icons.address, text: "Address" },
//         { icon: Icons.airdrop, text: "Airdrop" }
//     ];
// }

export component TabBtns inherits Rectangle {
    in-out property <[{ icon: image, text: string }]> items;
    in-out property <length> font-size: Theme.default-font-size;
    in-out property <bool> enable: true;

    private property <length> btn-height;
    private property <length> btn-width;
    private property <length> btn-pos-x;
    private property <length> btn-pos-y;
    private property <int> selected-index;
    private property <bool> init-delay-flag;

    callback clicked(index: int);

    public function update-selected-index(index: int) {
        selected-index = index;
    }

    background: Theme.secondary-background;
    border-radius: Theme.border-radius;
    width: hbox.preferred-width;
    height: hbox.preferred-height;

    Timer {
        interval: 100ms;
        running: true;
        triggered() => {
            self.running = false;
            init-delay-flag = !init-delay-flag;
        }
    }

    Rectangle {
        x: btn-pos-x;
        y: btn-pos-y;
        width: btn-width;
        height: btn-height;
        background: Theme.base-background;
        border-radius: Theme.border-radius;

        animate x, y, width, height {
            duration: Theme.default-animate-duration;
            easing: ease-in-out;
        }
    }

    hbox := HorizontalLayout {
        padding: Theme.padding;

        for item[index] in items: Rectangle {
            width: btn.preferred-width;
            height: btn.preferred-height;
            border-radius: Theme.border-radius;

            private property <int> inner-selected-index <=> root.selected-index;
            changed inner-selected-index => {
                if (selected-index == index) {
                    self.update-btn();
                }
            }

            private property inner-init-delay-flag <=> init-delay-flag;
            changed inner-init-delay-flag => {
                if (index == root.selected-index) {
                    self.update-btn();
                }
            }

            function update-btn() {
                btn-width = self.preferred-width - Theme.spacing * 2;
                btn-height = Math.max(btn-height, self.preferred-height);
                btn-pos-x = self.x + Theme.padding;
                btn-pos-y = self.y;
            }

            btn := TextBtn {
                icon: item.icon;
                text: item.text;
                font-size: root.font-size;
                icon-size: self.font-size;
                enabled-toucharea: root.enable;
                colorize: selected-index == index ? (Theme.is-dark ? Theme.light-text-color : Theme.primary-text-color) : Theme.have-read-text-color;

                clicked => {
                    selected-index = index;
                    root.clicked(index);
                    update-btn();
                }
            }
        }
    }
}
