import { Theme, Icons } from "../theme.slint";
import { IconBtn } from "./icon-btn.slint";

export component Tag inherits Rectangle {
    in-out property text <=> tag.text;
    in-out property text-color <=> tag.color;
    in-out property font-size <=> tag.font-size;
    in-out property<bool> is-show-close-btn: false;
    in-out property<length> hpadding: Theme.padding;
    in-out property<length> vpadding: Theme.padding;

    callback close <=> close-btn.clicked;

    border-radius: Theme.border-radius;
    background: Theme.thirdly-brand-color;

    HorizontalLayout {
        padding-left: root.hpadding;
        padding-right: root.hpadding;
        padding-top: root.vpadding;
        padding-bottom: root.vpadding;

        tag := Text {
            vertical-alignment: center;
            font-size: Theme.default-font-size - 4px;
            color: Theme.invert-base-color;
        }

        VerticalLayout {
            alignment: LayoutAlignment.center;
            width: root.is-show-close-btn ? self.preferred-width : 0px;
            padding-left: Theme.padding * 2;

            close-btn := IconBtn {
                visible: root.is-show-close-btn;
                icon: Icons.close;
                icon-size: tag.preferred-height * 0.6;
                show-icon-hover-background: false;
                colorize: Theme.dark-text-color;
            }
        }
    }
}
