import { Theme } from "../theme.slint";
import { Util } from "../util.slint";
import { Label } from "label.slint";
import { CenterLayout } from "center-layout.slint";
import { ToastStatus } from "def.slint";

export global ToastSetting {
    in-out property <string> text;
    in-out property <ToastStatus> status;
    in-out property <bool> is-hover;
    in-out property <bool> is-timeout: true;

    public function set(text: string, status: ToastStatus) {
        self.text = text;
        self.status = status;
    }
}

export component Toast inherits Rectangle {
    in-out property <length> inner-max-width: 300px;

    callback clicked <=> touch.clicked;

    width: hbox.preferred-width + Theme.padding;
    height: hbox.preferred-height;
    border-radius: Theme.border-radius;
    border-color: Theme.base-border-color;
    background: Util.text-color(ToastSetting.status);

    hbox := HorizontalLayout {
        alignment: LayoutAlignment.center;
        spacing: Theme.spacing;
        padding: Theme.padding * 2;

        CenterLayout {
            img := Image {
                width: txt.font-size * 1.2;
                height: self.width;
                source: Util.icon-source(ToastSetting.status);
                colorize: Colors.white;
            }
        }

        txt := Label {
            max-width: root.inner-max-width;
            font-size: Theme.title4-font-size;
            color: img.colorize;
            wrap: word-wrap;
            text: ToastSetting.text;
        }
    }

    touch := TouchArea {
        mouse-cursor: self.has-hover ? MouseCursor.pointer : MouseCursor.default;
        changed has-hover => {
            if (self.has-hover) {
                ToastSetting.is-hover = true;
            } else {
                ToastSetting.is-hover = false;
            }
        }
    }
}
