import { TextEdit, Palette, ScrollView } from "std-widgets.slint";
import { Theme } from "theme.slint";

export component TxtEditStd inherits Rectangle {
    clip: true;
    forward-focus: edit;
    border-radius: Theme.border-radius;
    border-width: edit.has-focus ? Theme.default-border-width * 2 : Theme.default-border-width;
    border-color: edit.has-focus ? Theme.thirdly-brand-color : Theme.base-border-color;

    in-out property <string> placeholder;
    in-out property <length> inner-padding: 0;
    in-out property text <=> edit.text;
    in-out property font-size <=> edit.font-size;

    callback edited <=> edit.edited;

    public function clear() {
        root.text = "";
    }

    public function copy() {
        edit.copy();
    }

    public function clear-editor-focus() {
        edit.clear-focus();
    }

    hbox := HorizontalLayout {
        padding: root.inner-padding;

        edit := TextEdit {
            font-size: Theme.default-font-size;
        }
    }

    if !placeholder.is-empty && root.text.is-empty: Text {
        x: root.inner-padding + Theme.padding * 2;
        y: root.inner-padding + Theme.padding * 4;
        text: placeholder;
        font-size: root.font-size;
        color: Theme.placeholder-text-color;
    }
}

export component TxtEdit inherits Rectangle {
    forward-focus: edit;
    border-radius: Theme.border-radius;
    border-width: edit.has-focus && !read-only ? Theme.default-border-width * 2 : Theme.default-border-width;
    border-color: self.default-border-color;

    in-out property <bool> enabled: true;
    in-out property <string> placeholder;
    in-out property <length> inner-padding: Theme.padding * 2;
    in-out property text <=> edit.text;
    in-out property font-size <=> edit.font-size;
    in-out property text-color <=> edit.color;
    in-out property <bool> read-only;
    out property <bool> has-focus: edit.has-focus;
    out property <color> default-border-color: !root.enabled ? Theme.base-border-color : (edit.has-focus && !read-only ? Theme.thirdly-brand-color : (read-only ? Theme.regular-text-color : Theme.base-border-color));

    callback edited(text: string);
    callback key-pressed <=> edit.key-pressed;

    public function copy() {
        return edit.copy();
    }

    public function clear() {
        root.text = "";
    }

    public function clear-editor-focus() {
        edit.clear-focus();
    }

    function ensure-show-cursor() {
        if (flick.viewport-height <= flick.height) {
            flick.viewport-y = 0;
        } else {
            if (-flick.viewport-y + edit.font-size * 2 < flick.viewport-height - flick.height) {
                return;
            }
            flick.viewport-y = -flick.viewport-height + flick.height;
        }
    }

    flick := ScrollView {
        VerticalLayout {
            padding: inner-padding;

            edit := TextInput {
                single-line: false;
                wrap: word-wrap;
                color: root.enabled && !root.read-only ? Theme.primary-text-color : Theme.disabled-color;
                font-size: Theme.default-font-size;
                read-only: root.read-only || !root.enabled;

                edited() => {
                    ensure-show-cursor();
                    root.edited(root.text);
                }
            }
        }
    }

    if !placeholder.is-empty && root.text.is-empty: Text {
        x: root.inner-padding;
        y: self.x;
        text: placeholder;
        font-size: root.font-size;
        color: Theme.placeholder-text-color;
    }
}
