import { Util } from "util.slint";
import { Logic } from "../logic.slint";
import { Theme, Icons } from "theme.slint";
import { Label } from "./label.slint";
import { CancelBtn, ConfirmBtn } from "./btn.slint";

export component UnsaveChangeDialog inherits Rectangle {
    height: vbox.preferred-height;
    width: self.preferred-width / Theme.golden-ratio;
    preferred-width: vbox.preferred-width;
    background: Theme.base-background;
    border-radius: Theme.border-radius;
    border-width: Theme.default-border-width;
    border-color: Theme.base-border-color;

    in-out property <bool> is-prevent-event-forward: false;
    in-out property <string> title: Logic.tr("Close Project");
    in-out property vbox-preferred-width <=> vbox.preferred-width;

    callback cancelled <=> cancel-btn.clicked;
    callback unsaved <=> unsave-btn.clicked;
    callback saved <=> save-btn.clicked;

    if is-prevent-event-forward: TouchArea { }

    vbox := VerticalLayout {
        alignment: start;
        padding: Theme.padding * 4;
        spacing: Theme.spacing * 4;

        title-label := Label {
            text: root.title;
            color: Theme.primary-text-color;
            font-size: Theme.title1-font-size;
        }

        content-lb := Label {
            wrap: word-wrap;
            color: Theme.secondary-text-color;
            font-size: Theme.title4-font-size;
            text: Logic.tr("Save project or not?");
        }

        HorizontalLayout {
            alignment: end;
            spacing: Theme.spacing * 4;

            cancel-btn := CancelBtn {
                text: Logic.tr("Cancel");
            }

            unsave-btn := CancelBtn {
                text: Logic.tr("Unsave");
                icon: Icons.ignore-light;
            }

            save-btn := ConfirmBtn {
                text: Logic.tr("Save");
                icon: Icons.save-light;
            }
        }
    }
}
