import { Theme, Store, TabIndex, SettingDetailIndex, Logic, Icons } from "../def.slint";
import { SettingDialog, AboutDialog, HorizontalSettingIconsBar } from "../setting/desktop.slint";
import { Blanket, StatusBar, Divider, AboutSetting, ToolTip, ToolTipSetting, PopupAction, PopupActionSetting } from "../../base/widgets.slint";
import { Home } from "home.slint";


component HorizontalStatusBar inherits StatusBar {
    background: Theme.secondary-background;
    is-show-icon: true;
    icon: Icons.brand;
    title: AboutSetting.app-name;
    is-show-tip: true;

    HorizontalLayout {
        padding-right: Theme.padding * 2;

        HorizontalSettingIconsBar {
            icon-size: Theme.default-font-size;
            h-spacing: Theme.spacing * 3;
            show-icon-hover-background: false;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
        }

        VerticalLayout {
            alignment: LayoutAlignment.center;
            Divider {
                height: Theme.default-font-size;
                width: 2px;
            }
        }
    }
}

export component DesktopPanel inherits Rectangle {
    private property <bool> is-show-setting-dialog: Store.current-tab-index == TabIndex.Setting;
    private property <bool> is-show-about-dialog: Store.current-tab-index == TabIndex.About;

    private property <length> home-height: self.height;

    background: Theme.base-background;

    VerticalLayout {
        if Store.setting-preference.no-frame: HorizontalStatusBar {
            init => {
                root.home-height = root.height - self.preferred-height;
            }
        }

        Home {
            // height: root.home-height;
        }
    }

    if is-show-setting-dialog || is-show-about-dialog: Blanket {
        clicked => {
            Logic.switch-tab(TabIndex.Back);
        }
    }

    if is-show-setting-dialog: SettingDialog {
        width: Math.min(1300px, root.width * 0.8);
    }

    if is-show-about-dialog: AboutDialog {
        width: Math.min(600px, root.width * 0.8);
    }

    if PopupActionSetting.is-show: PopupAction {
        window-width: root.width;
        window-height: root.height;
    }

    if ToolTipSetting.is-show: ToolTip {
        window-width: root.width;
        window-height: root.height;
    }
}
