import { Dialog } from "./dialog.slint";
import { Store } from "../store.slint";
import { Util } from "../util.slint";
import { Logic } from "../logic.slint";
import { Theme, Icons } from "../theme.slint";
import { Label } from "./label.slint";
import { CancelBtn, TextBtn } from "./btn.slint";

export global ConfirmDialogSetting {
    in-out property <bool> show;
    out property <string> title-type: "warning";
    out property <string> title-text: "警告";
    out property <string> body-text;
    out property <string> handle-type;
    out property <string> user-data;

    public function set(show: bool, title-type: string, title-text: string, body-text: string, handle-type: string, user-data: string) {
        self.show = show;
        self.title-type = title-type;
        self.title-text = title-text;
        self.body-text = body-text;
        self.handle-type = handle-type;
        self.user-data = user-data;
    }
}

export component ConfirmDialogDialog inherits Rectangle {
    preferred-width: 200px;
    height: vbox.preferred-height;
    background: Theme.base-background;
    border-radius: Theme.border-radius;

    in-out property <bool> is-prevent-event-forward: false;
    in-out property <string> title: ConfirmDialogSetting.title-text;

    if is-prevent-event-forward: TouchArea { }

    vbox := VerticalLayout {
        alignment: start;
        padding: Theme.padding * 4;
        spacing: Theme.spacing * 4;

        title-label := Label {
            text: root.title;
            color: Theme.primary-text-color;
            font-size: Theme.title1-font-size;
        }

        Label {
            wrap: word-wrap;
            color: Theme.secondary-text-color;
            font-size: Theme.title4-font-size;
            text: ConfirmDialogSetting.body-text;
        }

        HorizontalLayout {
            alignment: end;
            spacing: Theme.spacing * 4;

            TextBtn {
                text: Logic.tr(Store.is-cn, "取消");
                icon: Icons.cancel;

                clicked => {
                    ConfirmDialogSetting.show = false;
                }
            }

            TextBtn {
                icon: Icons.success;
                text: Logic.tr(Store.is-cn, "确认");

                clicked => {
                    Logic.handle-confirm-dialog(ConfirmDialogSetting.handle-type, ConfirmDialogSetting.user-data);
                    ConfirmDialogSetting.show = false;
                }
            }
        }
    }
}
