export enum LoadingStatus {
    Loading,
    Fail,
    Success,
}

export enum PrioritizationFeeStatus {
    Slow,
    Normal,
    Fast,
}

export enum ToastStatus {
    Success,
    Info,
    Warning,
    Danger,
}

export enum ComponentPosition {
    Top,
    Left,
    Bottom,
    Right
}

export struct AppPosType {
    x: length,
    y: length,
}

export struct TreeEntry {
    is-open: bool,
    key: string,
    parent-node: string,
    current-node: string,
    icon: image,
}

export struct SideBarChildEntry {
    key: string,
    title: string,
    icon: image,
}

export struct SideBarEntry {
    key: string,
    is-open: bool,
    category: string,
    icon: image,
    children: [SideBarChildEntry],
}

