export enum LoadingStatus {
    Loading,
    Fail,
    Success,
}

export enum PrioritizationFeeStatus {
    Slow,
    Normal,
    Fast,
}

export enum ToastStatus {
    Success,
    Info,
    Warning,
    Danger,
    None,
}

export enum LayoutType {
    Horizontal,
    Vertical,
}

export enum ComponentPosition {
    Top,
    Left,
    Bottom,
    Right
}

export struct AppPosType {
    x: length,
    y: length,
}
