import { Theme, Icons } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { IconBtn } from "./icon-btn.slint";
import { CenterLayout } from "./center-layout.slint";
import { TextBtn } from "./btn.slint";

export component Dialog inherits Rectangle {
    in-out property <string> title;
    in-out property <color> title-bg: Theme.secondary-brand-color;
    in-out property <bool> is-hide-close-btn: false;
    in-out property <bool> is-hide-bottom-btns: false;
    in-out property <bool> is-hide-confirm-btn: false;
    in-out property <bool> is-hide-cancel-btn: false;
    in-out property <bool> is-prevent-event-forward: false;

    in-out property <color> cancel-text-color: Theme.info-color;
    in-out property <color> confirm-text-color: Theme.third-brand-color;

    callback close <=> cancel-clicked;
    callback canceled <=> cancel-clicked;
    callback confirmed <=> ok-clicked;

    callback cancel-clicked();
    callback ok-clicked();

    width: 800px;
    height: vbox.preferred-height;
    background: Theme.base-background;
    border-radius: Theme.border-radius;
    clip: true;

    if is-prevent-event-forward: TouchArea { }

    vbox := VerticalLayout {
        alignment: space-between;

        if root.title != "": Rectangle {
            height: txt.preferred-height * 1.33;
            background: root.title-bg;
            txt := Text {
                color: Colors.white;
                font-size: Theme.title3-font-size;
                text: root.title;
            }

            if !is-hide-close-btn: HorizontalLayout {
                alignment: end;
                padding-right: Theme.padding;
                CenterLayout {
                    IconBtn {
                        width: Theme.icon-size;
                        icon: Icons.close;
                        colorize: txt.color;
                        show-icon-hover-background: false;
                        clicked => {
                            root.cancel-clicked();
                        }
                    }
                }
            }
        }

        VerticalLayout {
            @children
        }

        if !is-hide-bottom-btns: HorizontalLayout {
            alignment: LayoutAlignment.end;
            spacing: Theme.spacing * 8;
            padding: Theme.padding * 4;

            if !is-hide-cancel-btn: TextBtn {
                icon: Icons.cancel;
                text: Logic.tr("Cancel");
                text-color: root.cancel-text-color;
                colorize: self.text-color;

                clicked => {
                    root.cancel-clicked();
                }
            }

            if !is-hide-confirm-btn: TextBtn {
                icon: Icons.success;
                text: Logic.tr("Confirm");
                text-color: root.confirm-text-color;
                colorize: self.text-color;

                clicked => {
                    root.ok-clicked();
                }
            }
        }
    }
}
