import { Theme } from "../theme.slint";
import { IconBtn } from "icon-btn.slint";

export component ElevatedBtn inherits Rectangle {
    width: Math.max(45px, Theme.default-font-size + 30px);
    height: self.width;
    border-radius: root.width / 2;
    background: btn.has-hover ? Theme.secondary-background.darker(10%) : Theme.secondary-background;
    drop-shadow-blur: Theme.padding;
    drop-shadow-color: Theme.secondary-background-drop-shadow;

    in-out property icon <=> btn.icon;
    in-out property rotation-type <=> btn.rotation-type;

    callback clicked <=> btn.clicked;

    btn := IconBtn {
        icon-size: root.width * 0.65;
        show-icon-hover-background: false;
    }
}
