import { Theme } from "../theme.slint";
import { Util } from "../util.slint";

export component RecordIndicator inherits Rectangle {
    in-out property <bool> is-start;
    in-out property <length> size: Theme.icon-size;
    in-out property <duration> duration: 2s;
    in-out property <color> living-color: Theme.danger-color;

    width: root.size;
    height: self.width;

    if is-start: Rectangle {
        private property <float> progress: Util.progress-value(root.duration);

        width: progress < 0.5 ? root.size * progress * 2 : root.size * (1 - progress) * 2;
        height: self.width;
        border-radius: self.width / 2;
        background: root.living-color;
        drop-shadow-color: root.living-color.brighter(20%);
        drop-shadow-blur: Math.round(self.width / 1px * 0.5) * 1px;
    }
}
