import { Theme, Icons } from "../theme.slint";
import { Logic } from "../logic.slint";
import { Store } from "../store.slint";
import { IconBtn } from "./icon-btn.slint";
import { Label } from "./label.slint";
import { Head } from "./head.slint";
import { CancelBtn, ConfirmBtn } from "./btn.slint";
import { LineInput } from "line-input.slint";
import { SettingDetailInner, SettingDetailInnerVbox, SettingDetailLabel } from "./setting-detail.slint";

export component ResetPassword inherits Rectangle {
    in property <bool> is-show-header: true;

    private property <string> error-message;

    callback canceled();
    callback back();

    //(old-password, new-password-first, new-password-second) -> error-message
    callback confirmed(string, string, string) -> string;

    public function reset() {
        error-message = "";
        password-first-lineedit.text = "";
        password-second-lineedit.text = "";
    }

    forward-focus: password-old-lineedit;

    vbox := VerticalLayout {
        if is-show-header: Head {
            title: Logic.tr("Back");
            hbox-alignment: LayoutAlignment.start;
            clicked => {
                root.back();
            }
        }

        SettingDetailInner {
            vbox-alignment: LayoutAlignment.center;

            SettingDetailInnerVbox {
                HorizontalLayout {
                    alignment: LayoutAlignment.center;
                    Label {
                        text: Logic.tr("Reset password");
                        font-size: Theme.title1-font-size;
                        font-weight: Theme.bold-font-weight;
                    }
                }
            }

            SettingDetailInnerVbox {
                password-old-txt := SettingDetailLabel {
                    text: Logic.tr("Please enter old password");
                }

                HorizontalLayout {
                    spacing: Theme.spacing;

                    private property <bool> is-show-password;

                    password-old-lineedit := LineInput {
                        width: root.width - Theme.padding * 4;
                        placeholder-text: Logic.tr("At least 8 chars");
                        icon: parent.is-show-password ? Icons.eye : Icons.close-eye;
                        input-type: parent.is-show-password ? InputType.text : InputType.password;
                        is-show-icon: true;

                        edited => {
                            root.error-message = "";
                        }

                        clicked => {
                            parent.is-show-password = !parent.is-show-password;
                        }
                    }
                }
            }

            SettingDetailInnerVbox {
                password-first-txt := SettingDetailLabel {
                    text: Logic.tr("Please enter new password");
                }

                HorizontalLayout {
                    spacing: Theme.spacing;

                    private property <bool> is-show-password;

                    password-first-lineedit := LineInput {
                        width: root.width - Theme.padding * 4;
                        placeholder-text: Logic.tr("At least 8 chars");
                        icon: parent.is-show-password ? Icons.eye : Icons.close-eye;
                        input-type: parent.is-show-password ? InputType.text : InputType.password;
                        is-show-icon: true;

                        edited => {
                            root.error-message = "";
                        }

                        clicked => {
                            parent.is-show-password = !parent.is-show-password;
                        }
                    }
                }
            }

            SettingDetailInnerVbox {
                password-second-txt := SettingDetailLabel {
                    text: Logic.tr("Please enter password again");
                }

                HorizontalLayout {
                    spacing: Theme.spacing;

                    private property <bool> is-show-password;

                    password-second-lineedit := LineInput {
                        width: root.width - Theme.padding * 4;
                        placeholder-text: Logic.tr("At least 8 chars");
                        icon: parent.is-show-password ? Icons.eye : Icons.close-eye;
                        input-type: is-show-password ? InputType.text : InputType.password;
                        is-show-icon: true;

                        edited => {
                            root.error-message = "";
                        }

                        clicked => {
                            parent.is-show-password = !parent.is-show-password;
                        }
                    }
                }
            }

            if root.error-message != "": SettingDetailInnerVbox {
                SettingDetailLabel {
                    color: Theme.danger-color;
                    text: root.error-message;
                }
            }

            HorizontalLayout {
                padding-top: Theme.padding * 5;
                padding-bottom: Theme.padding * 5;
                spacing: Theme.spacing * 8;

                CancelBtn {
                    text: Logic.tr("Cancel");
                    clicked => {
                        root.reset();
                        root.canceled();
                    }
                }

                ConfirmBtn {
                    text: Logic.tr("Confirm");

                    clicked => {
                        root.error-message = root.confirmed(password-old-lineedit.text, password-first-lineedit.text, password-second-lineedit.text);
                    }
                }
            }
        }
    }
}
