import { Theme } from "../theme.slint";
import { Slider } from "slider.slint";

export component SoundSliderPopup inherits PopupWindow {
    in-out property <float> current-sound;
    out property <length> inner-height: svbox.preferred-height;

    callback sound-changed(sound: int);

    y: -svbox.preferred-height + Theme.padding * 2;
    width: Theme.default-font-size * 3;
    opacity: 0;

    svbox := VerticalLayout {
        spacing: Theme.spacing * 2;
        padding-top: Theme.padding * 4;
        padding-bottom: Theme.padding * 4;

        HorizontalLayout {
            alignment: LayoutAlignment.center;

            sound-lider := Slider {
                width: Theme.default-font-size;
                height: Theme.default-font-size * 10;
                finished-progress-color: Theme.thirdly-brand-color;
                indicator-size: self.width * 1.33;
                orientation: Orientation.vertical;
                value: root.current-sound;

                changed(v) => {
                    if (root.current-sound == Math.round(v)) {
                        return;
                    }
                    root.current-sound = Math.round(v);
                    root.sound-changed(root.current-sound);
                }
            }
        }
    }
}
