import { TextEdit, Palette } from "std-widgets.slint";
import { Theme } from "../theme.slint";

export component TxtEdit inherits Rectangle {
    border-width: edit.has-focus ? 2px : 1px;
    border-radius: Theme.border-radius;
    border-color: edit.has-focus ? Theme.thirdly-brand-color : Theme.base-border-color;
    forward-focus: edit;
    clip: true;

    in-out property text <=> edit.text;
    in-out property <length> inner-padding: 0;

    callback edited <=> edit.edited;

    public function clear() {
        root.text = "";
    }

    public function copy() {
        edit.copy();
    }

    hbox := HorizontalLayout {
        padding: root.inner-padding;

        edit := TextEdit {
            font-size: Theme.default-font-size;
        }
    }
}
