import { Theme, Icons } from "../../theme.slint";
import { Logic } from "../../logic.slint";

import { CircleProgress } from "../../base/widgets.slint";
import { Util } from "../../util.slint";

component Body inherits Rectangle {
    VerticalLayout {
        alignment: center;
        spacing: Theme.spacing * 4;

        HorizontalLayout {
            alignment: LayoutAlignment.center;
            CircleProgress {
                progress: Util.progress-value(5s);
            }
        }
    }
}

export component Home inherits Rectangle {
    Body { }
}
