import { Util } from "./util.slint";
import { Logic } from "./logic.slint";
import { Theme, Icons } from "./theme.slint";
import { Store, SettingDetailIndex, DeviceType, SettingProxy } from "./store.slint";
import { Panel } from "./panel/panel.slint";
import { LoadingStatus, Toast, IconsDialogSetting, IconsDialog, ConfirmDialogDialog, ConfirmDialogSetting, Blanket, LandingPage, AboutSetting, ToastSetting, ToastStatus, AppPosType, StatusBar } from "./base/widgets.slint";

export component AppWindow inherits Window {
    preferred-width: Theme.default-width;
    preferred-height: Theme.default-height;
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
    background: Theme.base-background;
    title: AboutSetting.app-name;
    icon: Icons.brand;
    no-frame: !Store.setting-ui.is-use-system-bar;

    VerticalLayout {
        if root.no-frame: StatusBar {
            background: pink;
            is-show-icon: true;
            icon: root.icon;
            title: root.title;
        }

        Panel { }
    }

    if IconsDialogSetting.show || ConfirmDialogSetting.show: Blanket {
        clicked => {
            IconsDialogSetting.show = false;
            ConfirmDialogSetting.show = false;
        }
    }

    if IconsDialogSetting.show: IconsDialog {
        is-prevent-event-forward: true;
        select-index(handle-type, index, user-data) => {
        }
    }

    if ConfirmDialogSetting.show: ConfirmDialogDialog {
        is-prevent-event-forward: true;
        width: Math.min(root.width * 0.9, 380px);
    }

    if ToastSetting.text != "": Toast {
        x: root.width / 2 - self.width / 2;
        y: 50px;
        inner-max-width: root.width * 80%;
        clicked => {
            Logic.copy-to-clipboard(ToastSetting.text);
        }
    }

    if Store.is-show-landing-page: LandingPage {
        details: [
            {
                picture: Icons.landing-account,
                description: "",
            },
            {
                picture: Icons.landing-send,
                description: "",
            },
            {
                picture: Icons.landing-welcome,
                description: "",
            }
        ];
        skipped => {
            Store.is-show-landing-page = false;
        }
    }
}

export {
    AppPosType, Util, Logic, Store, Theme, Icons, IconsDialogSetting, LoadingStatus, SettingDetailIndex, AboutSetting, ToastSetting, ToastStatus, DeviceType , SettingProxy
    }
