import { Store,  SettingPreference, SettingProxy, TabIndex, SettingDetailIndex } from "store.slint";

import { SideBarEntry } from "base/def.slint";

export global Logic {
    callback update-cache-size();
    callback remove-all-cache();

    callback copy-to-clipboard(string);
    callback copy-from-clipboard() -> string;

    callback get-setting-preference() -> SettingPreference;
    callback set-setting-preference(SettingPreference);

    callback get-setting-proxy() -> SettingProxy;
    callback set-setting-proxy(SettingProxy);

    pure callback inner-tr(bool, string) -> string;
    inner-tr(is-cn, text) => {
        return text;
    }

    pure public function tr(text: string) -> string {
        inner-tr(Store.is-cn, text)
    }

    public function switch-setting-detail(index: SettingDetailIndex) {
        if (Store.current-setting-detail-index == index) {
            return;
        }
        Store.current-setting-detail-index = index;
    }

    public function switch-tab(index: TabIndex) {
        if (Store.current-tab-index == index) {
            return;
        }
        Store.current-tab-index = index;
    }

    //////////////////////////////// Logic Start  ////////////////////////////////

    pure callback generate-search-values([SideBarEntry]) -> [string];

    // (entries, search-value) -> entry
    pure callback get-sidebar-key-from-search-values([SideBarEntry], string) -> string;

    //////////////////////////////// Logic End  ////////////////////////////////

}
