import { Store,  SettingUI, TabIndex} from "store.slint";

export global Logic {
    callback update-cache-size();
    callback remove-all-cache();

    callback copy-to-clipboard(string);
    callback copy-from-clipboard() -> string;

    callback get-setting-ui() -> SettingUI;
    callback set-setting-ui(SettingUI);

    pure callback inner-tr(bool, string) -> string;
    inner-tr(is-cn, text) => {
        return text;
    }

    pure public function tr(text: string) -> string {
        inner-tr(Store.is-cn, text)
    }

    public function switch-tab(tab-index: TabIndex) {
        Store.current-tab-index = tab-index;
    }
}
