export enum DeviceType {
    Desktop,
    Mobile,
}

export enum TabIndex {
    Home,
    Setting,
    None,
}

export enum SettingDetailIndex {
    Home,
    Preference,
    Proxy,
    About,
    Help,
    Donate,
    None,
}

export struct SettingPreference {
    win-width: string,
    win-height: string,
    font-size: string,
    font-family: string,
    language: string,
    always-on-top: bool,
    no-frame: bool,
    is-dark: bool,
}

export struct SettingProxy {
    proxy-type: string,
    http-url: string,
    http-port: string,
    socks5-url: string,
    socks5-port: string,
}

//////////////////////////////// Logic Struct Start ////////////////////////////////
export enum ComponentIndex {
    None,
    Tree,
    Step,
    Progress,
    Slider,
    Button,
    Toast,
    Rate,
    Pagination,
    RecordIndicator,
    ToolTip,
    BreadCrumb,
    Skeleton,
    PinCodes,
    Select,
    Collapse,
    Input,
    Badge,
    Label,
    Tag,
    Loading,
    TabBtn,
    PopupAction,
    Banner,
    Divider,
    Link,
    Blanket,
    Avatar,
    Brand,
    Empty,
    LandingPage,
    StatusBar,
    Dialog,
    CenterLayout,
    SlideCard,
    ListTile,
    Drawer,
    News,
    Head,
    About,
    Help,
    AddressBook,
    Mnemonic,
    AccountBalance,
    LogIn,
    SignIn,
    Password,
    ResetPassword,
    Setting,
    TokenList,
    TokenSender,
    TokenRecipient,
    TransactionFee,
    WaitTransactionConfirmed,
    TransactionTile,
}

export struct ComponentEntry{
    title: string,
    component-index: ComponentIndex,
}

//////////////////////////////// Logic Struct End  ////////////////////////////////

export global Store {
    in-out property <DeviceType> device-type: DeviceType.Desktop;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page;

    in-out property <TabIndex> current-tab-index: TabIndex.Home;

    in-out property <SettingDetailIndex> previous-setting-detail-index: SettingDetailIndex.Preference;
    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.None;
    // in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Preference;

    in-out property <bool> is-cn: setting-preference.language == "cn";
    in-out property <SettingPreference> setting-preference: {
        win-width: 1500,
        win-height: 800,
        font-size: "24",
        font-family: "Source Han Sans CN",
        language: "en",
        always-on-top: false,
        no-frame: true,
        is-dark: false,
    };

    in-out property <[string]> helps: is-cn ? [
        "配置文件保存目录: ~/.config/slint-template",
        "数据库保存目录: ~/.local/share/slint-template",
    ] : [
        "Config directory: ~/.config/slint-template",
        "Data directory: ~/.local/share/slint-template",
    ];

    //////////////////////////////// Logic Start ////////////////////////////////

    in-out property <ComponentIndex> current-component-index: ComponentIndex.Tree;
    in-out property <[ComponentEntry]> component-entries: [
        {
            title: is-cn ? "树" : "Tree",
            component-index: ComponentIndex.Tree,
        },
        {
            title: is-cn ? "步骤" : "Step",
            component-index: ComponentIndex.Step,
        },
        {
            title: is-cn ? "进度条" : "Progress",
            component-index: ComponentIndex.Progress,
        },
        {
            title: is-cn ? "滑动条" : "Slider",
            component-index: ComponentIndex.Slider,
        },
        {
            title: is-cn ? "按钮" : "Button",
            component-index: ComponentIndex.Button,
        },
        {
            title: is-cn ? "弹出信息" : "Toast",
            component-index: ComponentIndex.Toast,
        },
        {
            title: is-cn ? "打分" : "Rate",
            component-index: ComponentIndex.Rate,
        },
        {
            title: is-cn ? "分页" : "Pagination",
            component-index: ComponentIndex.Pagination,
        },
        {
            title: is-cn ? "录制指示器" : "RecordIndicator",
            component-index: ComponentIndex.RecordIndicator,
        },
        {
            title: is-cn ? "工具提示" : "ToolTip",
            component-index: ComponentIndex.ToolTip,
        },
        {
            title: is-cn ? "面包屑" : "BreadCrumb",
            component-index: ComponentIndex.BreadCrumb,
        },
        {
            title: is-cn ? "骨架" : "Skeleton",
            component-index: ComponentIndex.Skeleton,
        },
        {
            title: is-cn ? "验证码" : "PinCodes",
            component-index: ComponentIndex.PinCodes,
        },
        {
            title: is-cn ? "选择下拉栏" : "Select",
            component-index: ComponentIndex.Select,
        },
        {
            title: is-cn ? "折叠" : "Collapse",
            component-index: ComponentIndex.Collapse,
        },
        {
            title: is-cn ? "输入" : "Input",
            component-index: ComponentIndex.Input,
        },
        {
            title: is-cn ? "徽章" : "Badge",
            component-index: ComponentIndex.Badge,
        },
        {
            title: is-cn ? "文本" : "Label",
            component-index: ComponentIndex.Label,
        },
        {
            title: is-cn ? "标签" : "Tag",
            component-index: ComponentIndex.Tag,
        },
        {
            title: is-cn ? "加载" : "Loading",
            component-index: ComponentIndex.Loading,
        },
        {
            title: is-cn ? "标签页" : "TabBtn",
            component-index: ComponentIndex.TabBtn,
        },
        {
            title: is-cn ? "弹出动作列表" : "PopupAction",
            component-index: ComponentIndex.PopupAction,
        },
        {
            title: is-cn ? "横幅" : "Banner",
            component-index: ComponentIndex.Banner,
        },
        {
            title: is-cn ? "分割线" : "Divider",
            component-index: ComponentIndex.Divider,
        },
        {
            title: is-cn ? "链接" : "Link",
            component-index: ComponentIndex.Link,
        },
        {
            title: is-cn ? "遮罩" : "Blanket",
            component-index: ComponentIndex.Blanket,
        },
        {
            title: is-cn ? "头像" : "Avatar",
            component-index: ComponentIndex.Avatar,
        },
        {
            title: is-cn ? "品牌" : "Brand",
            component-index: ComponentIndex.Brand,
        },
        {
            title: is-cn ? "空页面" : "Empty",
            component-index: ComponentIndex.Empty,
        },
        {
            title: is-cn ? "欢迎页面" : "LandingPage",
            component-index: ComponentIndex.LandingPage,
        },
        {
            title: is-cn ? "顶部状态栏" : "StatusBar",
            component-index: ComponentIndex.StatusBar,
        },
        {
            title: is-cn ? "弹框" : "Dialog",
            component-index: ComponentIndex.Dialog,
        },
        {
            title: is-cn ? "中间布局" : "CenterLayout",
            component-index: ComponentIndex.CenterLayout,
        },
        {
            title: is-cn ? "滑动卡片" : "SlideCard",
            component-index: ComponentIndex.SlideCard,
        },
        {
            title: is-cn ? "列表条目" : "ListTile",
            component-index: ComponentIndex.ListTile,
        },
        {
            title: is-cn ? "抽屉" : "Drawer",
            component-index: ComponentIndex.Drawer,
        },
        {
            title: is-cn ? "新闻" : "News",
            component-index: ComponentIndex.News,
        },
        {
            title: is-cn ? "头部" : "Head",
            component-index: ComponentIndex.Head,
        },
        {
            title: is-cn ? "关于" : "About",
            component-index: ComponentIndex.About,
        },
        {
            title: is-cn ? "帮助" : "Help",
            component-index: ComponentIndex.Help,
        },
        {
            title: is-cn ? "组记词" : "Mnemonic",
            component-index: ComponentIndex.Mnemonic,
        },
        {
            title: is-cn ? "账户余额" : "AccountBalance",
            component-index: ComponentIndex.AccountBalance,
        },
        {
            title: is-cn ? "注册" : "SignIn",
            component-index: ComponentIndex.SignIn,
        },
        {
            title: is-cn ? "登陆" : "LogIn",
            component-index: ComponentIndex.LogIn,
        },
        {
            title: is-cn ? "密码" : "Password",
            component-index: ComponentIndex.Password,
        },
        {
            title: is-cn ? "重置密码" : "ResetPassword",
            component-index: ComponentIndex.ResetPassword,
        },
        {
            title: is-cn ? "设置" : "Setting",
            component-index: ComponentIndex.Setting,
        },
        {
            title: is-cn ? "代币列表" : "TokenList",
            component-index: ComponentIndex.TokenList,
        },
        {
            title: is-cn ? "代币发送" : "TokenSender",
            component-index: ComponentIndex.TokenSender,
        },
        {
            title: is-cn ? "代币发送" : "TokenRecipient",
            component-index: ComponentIndex.TokenRecipient,
        },
        {
            title: is-cn ? "交易费用" : "TransactionFee",
            component-index: ComponentIndex.TransactionFee,
        },
        {
            title: is-cn ? "等待交易确认" : "WaitTransactionConfirmed",
            component-index: ComponentIndex.WaitTransactionConfirmed,
        },
        {
            title: is-cn ? "交易历史条目" : "TransactionTile",
            component-index: ComponentIndex.TransactionTile,
        },
    ];

    //////////////////////////////// Logic End  ////////////////////////////////
}
