export enum DeviceType {
    Desktop,
    Mobile,
}

export enum TabIndex {
    Home,
    Setting,
    None,
}

export enum SettingDetailIndex {
    Home,
    Preference,
    Proxy,
    About,
    Help,
    Donate,
    None,
}

export struct SettingPreference {
    win-width: string,
    win-height: string,
    font-size: string,
    font-family: string,
    language: string,
    always-on-top: bool,
    no-frame: bool,
    is-dark: bool,
}

export struct SettingProxy {
    proxy-type: string,
    http-url: string,
    http-port: string,
    socks5-url: string,
    socks5-port: string,
}

//////////////////////////////// Logic Struct Start ////////////////////////////////
export enum ComponentIndex {
    Tree,
    Step,
    Progress,
    Slider,
    Button,
    Toast,

////////////
    TabBtn,
    TabBtns,
    Label,
    Tag,
    NoMessageImg,
    NoDataImg,
    Divider,
    Link,
    Dialog,
    CenterLayout,
    ConfirmDialog,
    Blanket,
    IconsDialog,
    Head,
    Brand,
    LanguageDialog,
    ListTile,
    News,
    SlideCard,
    Drawer,
    Mnemonic,
    Avatar,

    About,
    AboutSetting,
    Help,
    ResetPassword,
    Banner,
    AccountBalance,

    StatusBar,
    CircleProgress,
    Rate,
    ProgressBar,
    RecordIndicator,
    ToolTip,
    Pagination,
    BreadCrumb,
    Skeleton,
    PinCodes,
    Badge,
    Select,
    Collapse,
    Search,

    PopupAction,
    PopupActionEntry,

    TokenTile,
    TokenTileEntry,
    TokenTileWithSwitchEntry,
    TokenList,
    TokenListWithSwitch,
    TokenSender,
    TokenRecipient,

    AddressBook,
    AddressBookEntry,
    AddressBookDetail,
    AddressBookSetting,

    TransactionFee,
    TransactionTile,
    TransactionTileEntry,
    TransactionTileStatus,
    WaitTransactionConfirmed,


    SignIn,
    Login,
    Password,





    Setting,
    SettingEntry,
    SettingEntryV2,
    SettingDetail,

    Loading,
    LandingPage,



    Input,
    TextEdit,
    LineInput,


}

//////////////////////////////// Logic Struct End  ////////////////////////////////

export global Store {
    in-out property <DeviceType> device-type: DeviceType.Desktop;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page;

    in-out property <TabIndex> current-tab-index: TabIndex.Home;

    in-out property <SettingDetailIndex> previous-setting-detail-index: SettingDetailIndex.Preference;
    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.None;
    // in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Preference;

    in-out property <bool> is-cn: setting-preference.language == "cn";
    in-out property <SettingPreference> setting-preference: {
        win-width: 1500,
        win-height: 800,
        font-size: "16",
        font-family: "Source Han Sans CN",
        language: "en",
        always-on-top: false,
        no-frame: true,
        is-dark: false,
    };

    in-out property <[string]> helps: is-cn ? [
        "配置文件保存目录: ~/.config/slint-template",
        "数据库保存目录: ~/.local/share/slint-template",
    ] : [
        "Config directory: ~/.config/slint-template",
        "Data directory: ~/.local/share/slint-template",
    ];

    //////////////////////////////// Logic Start ////////////////////////////////

    in-out property <ComponentIndex> current-component-index: ComponentIndex.Button;
    in-out property <[{title: string, component-index: ComponentIndex}]> component-entries: [
        {
            title: is-cn ? "树" : "Tree",
            component-index: ComponentIndex.Tree,
        },
        {
            title: is-cn ? "步骤" : "Step",
            component-index: ComponentIndex.Step,
        },
        {
            title: is-cn ? "进度条" : "Progress",
            component-index: ComponentIndex.Progress,
        },
        {
            title: is-cn ? "滑动条" : "Slider",
            component-index: ComponentIndex.Slider,
        },
        {
            title: is-cn ? "按钮" : "Button",
            component-index: ComponentIndex.Button,
        },
        {
            title: is-cn ? "弹出信息" : "Toast",
            component-index: ComponentIndex.Toast,
        }
    ];

    //////////////////////////////// Logic End  ////////////////////////////////
}
