export enum DeviceType {
    Desktop,
    Mobile,
}

export enum TabIndex {
    Home,
    Setting,
    None,
}

export enum SettingDetailIndex {
    Home,
    Preference,
    Proxy,
    About,
    Help,
    Donate,
    None,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    language: string,
    is-use-system-bar: bool,
    is-dark: bool,
}

export struct SettingProxy {
    proxy-type: string,
    http-url: string,
    http-port: string,
    socks5-url: string,
    socks5-port: string,
}

//////////////////////////////// Logic Struct Start ////////////////////////////////

//////////////////////////////// Logic Struct End  ////////////////////////////////

export global Store {
    in-out property <DeviceType> device-type: DeviceType.Desktop;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page;

    in-out property <TabIndex> current-tab-index: TabIndex.Home;

    in-out property <SettingDetailIndex> previous-setting-detail-index: SettingDetailIndex.Preference;
    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.None;

    in-out property <bool> is-cn: setting-ui.language == "cn";
    in-out property <SettingUI> setting-ui: {
        font-size: "16",
        font-family: "Source Han Sans CN",
        language: "en",
        is-use-system-bar: true,
        is-dark: false,
    };

    in-out property <[string]> helps: is-cn ? [
        "配置文件保存目录: ~/.config/slint-template",
        "数据库保存目录: ~/.local/share/slint-template",
    ] : [
        "Config directory: ~/.config/slint-template",
        "Data directory: ~/.local/share/slint-template",
    ];

//////////////////////////////// Logic Start ////////////////////////////////

//////////////////////////////// Logic End  ////////////////////////////////
}
