import { Theme, Icons } from "theme.slint";
import { ToastStatus } from "./base/def.slint";

export global Util {
    // (message, status)
    callback show-toast(string, ToastStatus);

    // (message-type, user-data)
    callback handle-confirm-dialog(string, string);

    callback string-fixed2(string) -> string;
    callback float-fixed2(float) -> string;

    // (browser, url) => void
    callback open-url(string, string);

    pure callback text-len(string) -> int;

    // (low-bound, up-bound) => void
    pure callback rand-int(int, int) -> int;

    pure callback qr-code(string) -> image;
    qr-code => {
        return Icons.no-data;
    }

    pure callback local-now(string) -> string;
    local-now => {
        return "12:34:45";
    }

    pure callback format_number_with_commas(string) -> string;
    format_number-with-commas(number-str) => {
        return number-str;
    }

    pure callback split-and-join-string(string, int, string) -> string;
    split-and-join-string(input, length, sep) => {
        return input;
    }

    public pure function text-color(status: ToastStatus) -> color {
        if (status == ToastStatus.Success) {
            return Theme.success-color;
        } else if (status == ToastStatus.Warning) {
            return Theme.warning-color.darker(10%);
        } else if (status == ToastStatus.Danger) {
            return Theme.danger-color;
        }
        return Theme.info-color;
    }

    public pure function icon-source(status: ToastStatus) -> image {
        if (status == ToastStatus.Success) {
            return @image-url("./images/success.svg");
        } else if (status == ToastStatus.Warning) {
            return @image-url("./images/warning.svg");
        } else if (status == ToastStatus.Danger) {
            return @image-url("./images/danger.svg");
        }
        return @image-url("./images/info.svg");
    }

    public pure function bound(low: int, value: int, height: int) -> int {
        return Math.max(low, Math.min(value, height));
    }

    pure public function get-token-icon(symbol: string, mint-address: string, icon-extension: string) -> image {
        return Icons.token;
    }
}
