import { Logic, Theme, Store, Util, Icons, SettingUI, SettingProxy, SettingDetailIndex } from "../def.slint";
import { IconBtn, SettingEntryV2, Head, SettingDetail, ToastStatus, About, Help, Dialog } from "../../base/widgets.slint";
import { Preference } from "components/preference.slint";
import { Donate } from "components/donate.slint";
import { Proxy } from "components/proxy.slint";

component LeftPanel inherits Rectangle {
    background: Theme.secondary-background;

    // (previous-index, current-index) -> void
    callback switch(SettingDetailIndex, SettingDetailIndex) -> bool;

    function update-index(index: SettingDetailIndex) {
        if (root.switch(Store.previous-setting-detail-index, index)) {
            Store.previous-setting-detail-index = index;
        }
    }

    Flickable {
        width: root.width;
        viewport-height: vbox.preferred-height;

        vbox := VerticalLayout {
            alignment: LayoutAlignment.start;

            SettingEntryV2 {
                text: Logic.tr("Preference");
                icon: Icons.ui;
                background: Store.current-setting-detail-index == SettingDetailIndex.Preference ? Theme.base-background : root.background;

                clicked => {
                    update-index(SettingDetailIndex.Preference);
                }
            }

            SettingEntryV2 {
                text: Logic.tr("Proxy");
                icon: Icons.proxy-light;
                background: Store.current-setting-detail-index == SettingDetailIndex.Proxy ? Theme.base-background : root.background;

                clicked => {
                    update-index(SettingDetailIndex.Proxy);
                }
            }

            SettingEntryV2 {
                text: Logic.tr("Help");
                icon: Icons.help-light;
                background: Store.current-setting-detail-index == SettingDetailIndex.Help ? Theme.base-background : root.background;

                clicked => {
                    update-index(SettingDetailIndex.Help);
                }
            }

            SettingEntryV2 {
                text: Logic.tr("Donate");
                icon: Icons.donate;
                background: Store.current-setting-detail-index == SettingDetailIndex.Donate ? Theme.base-background : root.background;

                clicked => {
                    update-index(SettingDetailIndex.Donate);
                }
            }
        }
    }
}

component RightPanel inherits Rectangle {
    public function preference-get() -> SettingUI {
        return preference.get();
    }

    public function proxy-get() -> SettingProxy {
        return proxy.get();
    }

    preference := Preference {
        visible: Store.current-setting-detail-index == SettingDetailIndex.Preference;
        is-show-header: false;
    }

    proxy := Proxy {
        visible: Store.current-setting-detail-index == SettingDetailIndex.Proxy;
        is-show-header: false;
    }

    if Store.current-setting-detail-index == SettingDetailIndex.Help: Help {
        is-show-header: false;
        entries: Store.helps;
    }

    if Store.current-setting-detail-index == SettingDetailIndex.Donate: Donate {
        is-show-header: false;
    }
}

component Setting inherits Rectangle {
    public function save(index: SettingDetailIndex) -> bool {
        if (index == SettingDetailIndex.Preference) {
            if (rp.preference-get().font-size == "") {
                Util.show-toast(Logic.tr("Input can not be empty"), ToastStatus.Warning);
                return false;
            }
            Logic.set-setting-ui(rp.preference-get());
        } else if (index == SettingDetailIndex.Proxy) {
            Logic.set-setting-proxy(rp.proxy-get());
        }
        return true;
    }

    HorizontalLayout {
        LeftPanel {
            width: Math.max(root.width * 0.3, 200px);
            switch(previous-index, current-index) => {
                if (!root.save(previous-index)) {
                    return false;
                }

                Logic.switch-setting-detail(current-index);
                return true;
            }
        }

        rp := RightPanel { }
    }
}

export component SettingDialog inherits Dialog {
    title: Logic.tr("Setting");
    is-hide-btns: true;
    is-prevent-event-forward: true;

    setting := Setting {
        height: 650px;
    }

    cancel-clicked => {
        setting.save(Store.current-setting-detail-index);
        Logic.switch-setting-detail(SettingDetailIndex.None);
    }
}

export component AboutDialog inherits Dialog {
    title: Logic.tr("About");
    is-hide-btns: true;
    is-prevent-event-forward: true;

    About {
        height: 650px;
        is-show-header: false;
    }

    cancel-clicked => {
        Logic.switch-setting-detail(SettingDetailIndex.None);
    }
}

export component SettingIconsBar inherits Rectangle {
    width: hbox.preferred-width;
    height: hbox.preferred-height;
    border-radius: Theme.border-radius;

    hbox := HorizontalLayout {
        padding: Theme.padding * 4;
        spacing: Theme.spacing * 4;

        IconBtn {
            icon: Icons.setting-fill;
            clicked => {
                Logic.switch-setting-detail(SettingDetailIndex.Preference);
            }
        }

        IconBtn {
            icon: Icons.about-fill;
            clicked => {
                Logic.switch-setting-detail(SettingDetailIndex.About);
            }
        }

        IconBtn {
            icon: Icons.github;
            clicked => {
                Util.open-url("Default","https://github.com/Heng30/slint-template");
            }
        }
    }
}
