import { Logic, Theme, Store, Util, Icons, SettingPreference, SettingDetailIndex } from "../def.slint";
import { Head, SettingEntry, SettingDetail, ToastStatus, About, Help } from "../../base/widgets.slint";
import { Preference } from "components/preference.slint";
import { Donate  } from "components/donate.slint";
import { Proxy  } from "components/proxy.slint";

component Body inherits VerticalLayout {
    alignment: start;
    spacing: Theme.spacing;

    head := Head {
        hbox-alignment: LayoutAlignment.start;
        icon: Icons.setting-fill;
        title: Logic.tr("Setting");
    }

    Flickable {
        viewport-height: vbox.preferred-height;

        vbox := VerticalLayout {
            spacing: Theme.spacing * 2;

            SettingEntry {
                text: Logic.tr("Preference");
                icon: Icons.ui;

                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.Preference);
                }
            }

            SettingEntry {
                text: Logic.tr("Proxy");
                icon: Icons.proxy-light;

                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.Proxy);
                }
            }

            SettingEntry {
                text: Logic.tr("About");
                icon: Icons.about-light;
                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.About);
                }
            }

            SettingEntry {
                text: Logic.tr("Help");
                icon: Icons.help-light;
                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.Help);
                }
            }

            SettingEntry {
                text: Logic.tr("Donate");
                icon: Icons.donate;
                clicked => {
                    Logic.switch-setting-detail(SettingDetailIndex.Donate);
                }
            }

            SettingEntry {
                text: Logic.tr("Github");
                icon: Icons.github;
                clicked => {
                    Util.open-url("Default","https://github.com/Heng30/slint-template");
                }
            }
        }
    }
}

export component Setting inherits Rectangle {
    init => {
        Logic.switch-setting-detail(SettingDetailIndex.Home);
    }

    if Store.current-setting-detail-index == SettingDetailIndex.Home: Body { }

    if Store.current-setting-detail-index != SettingDetailIndex.Home: Rectangle {
        if Store.current-setting-detail-index == SettingDetailIndex.Preference: Preference {
            back => {
                if (self.get().font-size == "") {
                    Util.show-toast(Logic.tr("Input can not be empty"), ToastStatus.Warning);
                    return;
                }

                Store.setting-preference.font-size = self.get().font-size;
                Store.setting-preference.font-family = self.get().font-family;
                Logic.set-setting-preference(self.get());
                Logic.switch-setting-detail(SettingDetailIndex.Home);
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.Proxy: Proxy {
            back => {
                Logic.switch-setting-detail(SettingDetailIndex.Home);
                Logic.set-setting-proxy(self.get());
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.About: About {
            back => {
                Logic.switch-setting-detail(SettingDetailIndex.Home);
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.Help: Help {
            entries: Store.helps;
            back => {
                Logic.switch-setting-detail(SettingDetailIndex.Home);
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.Donate: Donate {
            back => {
                Logic.switch-setting-detail(SettingDetailIndex.Home);
            }
        }
    }
}
